### ISSUE TITLE
Checkbox documentation needs two alignment options

### ISSUE THREAD

**Issue by krtk6160** [carbon-design-system/carbon-components-angular#1295]
## Detailed description

> Describe in detail the issue you're having.
The [Carbon Design System](https://www.carbondesignsystem.com/components/checkbox/usage/#alignment) checkbox page mentions vertical stacking and horizontal alignment. 
The documentation for carbon components angular does not mention anything relating to the alignment of checkbox groups, even though it is a pretty common use case to have it aligned in either of the two ways.

> Is this a feature request (new component, new icon), a bug, or a general issue?
General issue

> Is this issue related to a specific component?
Checkbox

**Comment by cal-smith** [comment]
To be clear, is this a documentation issue or a functionality issue? I.e. do we support both alignments but it's not documented, or do we need to support _and_ document both alignments?

**Comment by krtk6160** [comment]
The link specified in the OP suggests this is something supported in Carbon Components vanilla.
And from what I understand, carbon components angular is a wrapper on top of that.
So it would seem we need documentation of how to achieve this.
