### ISSUE TITLE
Combobox: Selection by default

### ISSUE THREAD

**Issue by granall** [carbon-design-system/carbon-components-angular#1430]
## Detailed description

>Describe in detail the issue you're having.

- We are using the combobox to filter a data table. An aggregate of all the data is selected by default. From there users can open the combobox to select specific stores. The data would then refresh to show stats specific to that store. 

- The issue: the "X" is visible by default because the aggregate option is selected. 

> Is this a feature request (new component, new icon), a bug, or a general issue?

- General issue

> Is this issue related to a specific component?

- Combobox

> What did you expect to happen? What happened instead? What would you like to see changed?

- What happened: The "X" shows by default because aggregate is selected.

- What we expected to happen/what we would like to see changed: Remove the "X" by default because it doesn't have a functional purpose.  It can cause confusion for the user. [See video](https://ibm.box.com/s/e5dx9r4qaof6949o9g2g31p5yw0v4sdl)

> What browser are you working in?

- Chrome

> What version of the Carbon Design System are you using?

- "carbon-components": "10.10.3"

- "carbon-components-angular": "3.53.5"

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

- Sterling Fulfillment Optimizer with Watson

**Comment by cal-smith** [comment]
There seems to be a bit of a mismatch between the functionality of the combobox and the intended design of that screen. It's not clear to me why a combobox should be used if you don't also want the ability to clear the input. Based on the video it seems like a dropdown would be a better choice.

Clearing the typed value is essential for any kind of search/filter ... I'd like to explore our options in this space before resorting to a hack like this - I have concerns that it will be abused, and put us out of line with the rest of the design system.

**Comment by granall** [comment]
Thanks for responding @cal-smith 

We ended up using a combobox because we didn't think the standard dropdown had search/filter functionality. Is that functionality available? 

In general, users should have the ability to clear the input. However, for our use case, we don't want the user to be able to clear the default selection.

**Comment by cal-smith** [comment]
Thanks for the extra context @granall!

> We ended up using a combobox because we didn't think the standard dropdown had search/filter functionality. Is that functionality available?

It is for multi-select, but this seems like a good opportunity to explore bringing it to single select in an intentional way. Our combobox does a lot of things as is (including things it probably shouldn't), so it would be good to make sure we have design clarity.

> In general, users should have the ability to clear the input. However, for our use case, we don't want the user to be able to clear the default selection.

Got it. However that raises a few issues around things like the user manually clearing the selection, what behaviors are appropriate for a default selection, and applicability across applications. If we can reach some level of consensus around filterable selection behaviour/default selection behaviour, then we can see what that API would look like.

This may also be a PAL question if we can't get any joy at the global level.

**Comment by granall** [comment]
@cal-smith What would you recommend as the next best step to take?

**Comment by cal-smith** [comment]
@granall I think starting the conversation on the Carbon side would be good ... I'm not sure what avenues you have available for raising issues like this, but I think opening a design issue on https://github.com/carbon-design-system/carbon would be a good start

**Comment by granall** [comment]
Thanks @cal-smith ! Will do!

**Comment by Akshat55** [comment]
Seems like the issue has been marked as completed upstream. Closing the issue here since clicking `clear` seems to clear the combo box now.
