### ISSUE TITLE
File Uploader Component is removing both first and second file on adding second file in Internet Explorer

### ISSUE THREAD

**Issue by dishantsikka** [carbon-design-system/carbon-components-angular#1562]
File Uploader Component is removing both first and second file on adding second file in Internet Explorer

## Detailed description

> Describe in detail the issue you're having.

I am trying to use File Uploader component in Angular. Requirement is to upload a Single File in Internet Explorer v10 or v11.
Adding a first file is working fine, but adding a second file is removing both first and second file.
Expectation is that on adding the second file, first file should be removed and second file should be added.
This is working as expected in Chrome, but is not working in Internet Explorer.

It would be great help, if someone please help with this issue.

> Is this a feature request (new component, new icon), a bug, or a general issue?

It could be a bug or general issue

> Is this issue related to a specific component?

Yes, ibm-file-uploader

> What did you expect to happen? What happened instead? What would you like to see changed?

Expectation is that on adding the second file, first file should be removed and second file should be added.

Instead, adding a second file is removing both first and second file.

I would like to see that on adding a second file, first file should be removed and second file should be added.

> What browser are you working in?

Internet Explorer and Chrome. It is working as expected in chrome, but is not working in Internet Explorer

> What version of the Carbon Design System are you using?

I have tried this on v10.14.0 and v10.21.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Delivery is by the end of this month. It has to be tested in time before that.

## Steps to reproduce the issue

Sorry I can't access this in IE, so unable to create a URL that could help looking into the issue.

1) User clicks on Add file. First file is uploaded successfully.
2) Now the user has changed his mind, and wants to add some other file.
3) If the User clicks on Add file again.
4) It removes the First file, which is fine, but it does not add second file.

## Additional information

In order to verify, that I am not doing something wrong, I have tried this with minimum properties of File Uploader component.
I am using below code:

* Screenshots or code

<ibm-file-uploader
[multiple]=false>

* Notes

**Comment by Akshat55** [comment]
Closing this, I don't think this is relevant anymore since IE11 is no longer supported. There have also been a few PRs that have changed the logic for keeping track of files uploaded.
