### ISSUE TITLE
Investigate fluid form components (possibly needs new components)

### ISSUE THREAD

**Issue by cal-smith** [carbon-design-system/carbon-components-angular#1594]
<img width="1272" alt="Screen Shot 2020-07-13 at 12 10 13 PM" src="https://user-images.githubusercontent.com/45505172/87327268-da84d900-c501-11ea-8afa-48407156019c.png">

**Comment by Akshat55** [comment]
Closing this issue in favor of: https://github.com/carbon-design-system/carbon-components-angular/issues/2769

We have specified the list of components that require fluid states, however, the feature is still marked experimental. It will be implemented based on community requirement. The feature will only be available in Carbon 11 (CCA@5+).
