### ISSUE TITLE
Add context when 'app-' demo components are used

### ISSUE THREAD

**Issue by cal-smith** [carbon-design-system/carbon-components-angular#1800]
We use `app-` prefixed components in storybook to work around limitations in storybook, we should call this out every time we use a demo component to reduce confusion. We should also link out to the source for the component.

**Comment by adinhtdsibm** [comment]
@cal-smith Any pointers on what exactly needs to be done here? If it is still open, I can work on it if it is related to Documentation.

**Comment by Akshat55** [comment]
This has been addressed in latest version of CCA which uses Storybook v7. We NOW link to the github story example as well.
