### ISSUE TITLE
Search input icon not displayed correctly

### ISSUE THREAD

**Issue by milanteo** [carbon-design-system/carbon-components-angular#1821]
> Describe in detail the issue you're having.
When input is rendered the search icon is displyed outside of it, could be the class attached to the svg element, currently is 'bx--search-magnifier', changing it to 'bx--search-magnifier-icon' fixes it.

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
Search Component

> What browser are you working in?
Brave Browser v1.24

> What version of the Carbon Design System are you using?
carbon-components: 10.35.0
carbon-components-angular: 4.49.0

![image](https://user-images.githubusercontent.com/24292225/118253860-b50e8600-b4aa-11eb-8219-6054368c2dbe.png)

**Comment by tw15egan** [comment]
This is related to https://github.com/carbon-design-system/carbon/issues/8460. I believe the easiest fix is to update the selector [here](https://github.com/IBM/carbon-components-angular/blob/master/src/search/search.component.html#L37) to `bx--search-magnifier-icon`

**Comment by Akshat55** [comment]
Closing as this has been resolved upstream and updated in v4.
