### ISSUE TITLE
Code Snippet Show More button doesn't seem to be working

### ISSUE THREAD

**Issue by dbrandl28** [carbon-design-system/carbon-components-angular#1899]
What package(s) are you using?
"carbon-components": "^10.41.0",
"carbon-components-angular": "^4.54.1",

Describe in detail the issue you're having.
I have quite a bit of output in a Code snippet box. It is expanded on initial display. There is a Show More button at the bottom, but clicking it just changes it to the Show Less button. Clicking the Show Less button just collapses the last line.

Is this issue related to a specific component?
This was working before we upgraded to Carbon V10 and Angular V4. Not sure when it broke.

What did you expect to happen? What happened instead? What would you like to
see changed?

I expected the output to initially be collapsed and then expanded after clicking the Show More button.

What browser are you working in?
Happens with both Firefox and Chrome.

What version of the Carbon Design System are you using? V10

Please create a reduced test case in CodeSandbox

Your sandbox appears to have the same problem.
https://angular.carbondesignsystem.com/?path=/story/components-code-snippet--multi

Additional information
This is a scrollable page with a lot of data before this screenshot was taken.  This is the initial display without clicking Show More.
![ShowMore](https://user-images.githubusercontent.com/23317227/132009221-d132a668-fcec-4d9b-a02f-082dd96a36b9.PNG)

![ShowLess](https://user-images.githubusercontent.com/23317227/132009228-ab80aaab-ac8f-4483-a2c6-c211c3fdf52c.PNG)

**Comment by dbrandl28** [comment]
Do you agree this is a bug in carbon-components-angular?

**Comment by anemonetea** [comment]
I've seen the same issue

**Comment by Akshat55** [comment]
Closing issue as it was resolved in v5. The fix to it required a breaking change.
