### ISSUE TITLE
How can we add a Footer?

### ISSUE THREAD

**Issue by ksurendra** [carbon-design-system/carbon-components-angular#1922]
## Detailed description

How can we add a Footer to a project built using this Carbon Angular components? There is no Footer component. Is there a way to add one? Or any examples of a footer added to this project?

> Is this a feature request (new component, new icon), a bug, or a general issue? 

General issue

> Is this issue related to a specific component?

No

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

Following the instructions https://github.com/IBM/carbon-components-angular to build a new angular project, add "carbon components" and "carbon angular components".

```
$ npx @angular/cli new my-project --style=scss
$ cd my-project
$ npm i --save carbon-components-angular carbon-components
```

## Additional information

Reposting here for visibility https://github.com/carbon-design-system/carbon-angular-starter/issues/53

**Comment by grenobnik** [comment]
I guess that one of the reasons is that the notion of a footer component does not exist in [Carbon Design System](https://www.carbondesignsystem.com/components/overview/). However, you can be inspired by community assets, that is an [IBM Footer](https://www.ibm.com/standards/carbon/components/footer/). Unfortunately, it is not implemented in Angular, but it might be possible to use a [Web Component](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-footer--default). There are plenty of "best practices" and guidelines for all kinds of elements found in web apps, see, for example [here](https://www.nngroup.com/articles/footers/).

**Comment by Akshat55** [comment]
Closing issue since `Footer` is not an carbon component. You can have a look at different PALs for guidelines on footer.
