### ISSUE TITLE
Found this bug in PaginationNav Basic

### ISSUE THREAD

**Issue by cduran** [carbon-design-system/carbon-components-angular#1923]
Found this bug in PaginationNav https://angular.carbondesignsystem.com/?path=/story/components-paginationnav--basic
https://user-images.githubusercontent.com/164527/139490519-74fd2ba4-b037-47bd-b2c4-12f4139984b1.mov

**Comment by Akshat55** [comment]
Tested in latest v4 and v5 - issue has been resolved hence closed issue.
