### ISSUE TITLE
Password Component Needed

### ISSUE THREAD

**Issue by dondre** [carbon-design-system/carbon-components-angular#1930]
Carbon Svelte's password component is missing from Angular. 
Can that be added? 
The first thing I'm working on is a Login page, seems essential.

**Comment by grenobnik** [comment]
There is no such "Login" or "Password" component in [Carbon Design System](https://www.carbondesignsystem.com/components/overview/) that can be directly implemented Angular.  However, there is a [Login pattern](https://www.carbondesignsystem.com/patterns/login-pattern/) which is described in detail. You can implement this pattern to fit your particular needs using more or less standard components available in carbon-components-angular. Then you can propose your solution (transformed into some kind of generic way) to be included in [Community Assets](https://www.carbondesignsystem.com/community/component-index/).

**Comment by hubertmalkowski** [comment]
I think this issue should rereviewed as [React Carbon](https://react.carbondesignsystem.com/?path=/story/components-textinput--toggle-password-visibility), [Svelte carbon](https://svelte.carbondesignsystem.com/components/PasswordInput)  and [Vue carbon](https://vue.carbondesignsystem.com/?path=/story/component-cvtextinput--password) provide this kind of component. Only carbon-components-angular falls a bit behind.

**Comment by Akshat55** [comment]
Unfortunately, I cannot seems to officially assign@maicongodinho to the issue for some reason, but he will be working on it!

**Comment by maicongodinho** [comment]
Hello everyone,

I appreciate your patience. Apologies for the delay; I was on vacation and transitioning between teams in my current job. The first version is now ready for your review and discussion in the pull request: [PR #2772](https://github.com/carbon-design-system/carbon-components-angular/pull/2772).

Thank you for your understanding.
