### ISSUE TITLE
The second dialog is below the first one

### ISSUE THREAD

**Issue by Zwezh** [carbon-design-system/carbon-components-angular#1931]
## Detailed description
After updating from 
`carbon-components-angular: 4.55.4 -> 4.55.5`

We got the strange thing like the first dialog is above the second one. This behavior is the same here:
https://angular.carbondesignsystem.com/?path=/story/components-modal--basic 

## Additional information
Angular version is `12.2.8`
Carbon-components version is `10.48.0`

**Comment by Akshat55** [comment]
The modal now maintains order in both v4 or v5. I don't have the PR number that resolved this, but we do have a story that indicates that this is working correctly. Closing issue is as it is no longer valid.
