### ISSUE TITLE
[IBM-notifications]: lowContrast outline applied to entire ibm-placeholder container (or the entire viewport), instead of just 1 notification

### ISSUE THREAD

**Issue by maahtiin** [carbon-design-system/carbon-components-angular#1945]
## Detailed description

While using dynamically generated lowContrast-notifications, i noticed the border applying on the div containing the notification, instead of the notification itself. This isn't really noticable when only showing 1 notification, but when there are 2 or more it does not adhere to the Carbon design specs.
On angular.carbondesignsystem.com, when rendering lowContrast notifications using the knobs, the border is applied on the entire storybook-frame instead of the toasts themselves.

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
Yes, namely dynamic toast-notifications generated through the ibm-notifications-service, which are rendered in the ibm-placeholder container. The ::before selector containing the border-width is not applied on the toast itself.

> What did you expect to happen? What happened instead? What would you like to see changed?
Each individual notification (toast) having its own border. The container-div and toasts should not need any overriding css to apply the borders to the separate toasts itself rather than the container-div. 

> What browser are you working in?
Safari, Chrome, Firefox

> What version of the Carbon Design System are you using?
"carbon-components": "^10.45.0",
"carbon-components-angular": "^4.55.4"

## Steps to reproduce the issue

[Codesandbox](https://codesandbox.io/s/carbon-components-angular-forked-leiqj?file=/src/app/app.module.ts)

1. Open the CodeSandbox
2. Generate one or more Toasts
3. See the (enlarged for test-purposes) green border around the viewport of the sandbox
4. Creating multiple toasts will create multiple overlapping borders
5. This issue is also present in the angular.carbondesignsystem.com storybook

**Comment by messaoudi-mounir** [comment]
Here a quick fix is to add  **position: relative;** to .**bx--toast-notification** 

`.bx--toast-notification {
  position: relative;
}
`

**Comment by maahtiin** [comment]
Thanks for the quick fix!

**Comment by Akshat55** [comment]
I believe this has been fixed, I don't see it happening anymore in latest v4 & latest carbon-components. Fix may have occurred upstream. Closing this issue, feel free to reopen if needed.
