### ISSUE TITLE
ibm-sidenav-item has multiple accessibility issues

### ISSUE THREAD

**Issue by rutasip** [carbon-design-system/carbon-components-angular#2103]
## Detailed description

This is related to the \<ibm-sidenav-item> element inside the ui-shell.

**What currently gets rendered in the DOM:**

<img width="304" alt="Screenshot 2022-05-09 at 21 27 38" src="https://user-images.githubusercontent.com/29533816/167473669-1e0c3d58-97fc-4e02-b7c2-d82befb1a7a4.png">

**What needs to get rendered instead:**

<img width="290" alt="Screenshot 2022-05-09 at 21 28 42" src="https://user-images.githubusercontent.com/29533816/167473843-0b87bf78-4c74-423e-a374-7b2403c1f808.png">

**Problem:**
\<ibm-sidenav-item> element between \<ul> and \<li> elements.

From the Lighthouse report:
1. List items (\<li>) are not contained within \<ul> or \<ol> parent elements.
https://web.dev/listitem/?utm_source=lighthouse&utm_medium=cli

2. Lists do not contain only \<li> elements and script supporting elements (\<script> and \<template>).
https://web.dev/list/?utm_source=lighthouse&utm_medium=devtools

## Possible fix
Use attribute selector for ibm-sidenav-item. That will very likely be a breaking change.

**Comment by Akshat55** [comment]
This change will NOT be made in current major version (v4). This will be addressed in carbon-components-angular v5 since major changes to the template are required. 

This includes changes being made to Accordion & context menu as well.
