### ISSUE TITLE
[Pagination] Duplicated currentPage text when using "pagesUnknown"

### ISSUE THREAD

**Issue by yuriybelike** [carbon-design-system/carbon-components-angular#2199]
## Detailed description

> Describe in detail the issue you're having.

**When using the pagination component, along with the `pagesUnknown` Input, the component shows the current page number twice, "1 page 1" _(see screenshot)_.**

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Pagination

> What did you expect to happen? What happened instead? What would you like to see changed?

**For the component to show "page 1", instead of "1 page 1"**

> What browser are you working in?

Chrome 

> What version of the Carbon Design System are you using?

Latest, issue can be observed in the official storybook

## Steps to reproduce the issue

1. Go to https://angular.carbondesignsystem.com/?path=/story/components-pagination--basic
2. Go to the knobs tab
3. Enable "Total number of items unknown" & disable "Show the page selects"

## Additional information

![image](https://user-images.githubusercontent.com/60257988/178467211-17aa91e2-32e0-4c34-aebe-13a289a7e980.png)

**Comment by Akshat55** [comment]
Going to have to run this by @IBM/carbon-design-system, will reference this issue there to keep you informed.

**Comment by Akshat55** [comment]
Will be released in carbon 11, seems like the styles have not been updated for v10. 😞
