### ISSUE TITLE
Setting checkbox as disabled in reactive forms results in TypeError

### ISSUE THREAD

**Issue by anemonetea** [carbon-design-system/carbon-components-angular#2228]
## Detailed description

![Screen Shot 2022-08-25 at 11 57 46 AM](https://user-images.githubusercontent.com/26636906/186713438-39973373-5f26-4a71-a4f3-e59621b7709c.png)

Relevant Carbon code: https://github.com/IBM/carbon-components-angular/blob/64010af468042741cf2fc796a94f801d26499d18/src/checkbox/checkbox.component.ts#L315-L318

## Steps to reproduce the issue

Codesandbox: https://codesandbox.io/s/carbon-components-angular-checkbox-typeerror-sejsyl?file=/src/app/app.component.html

**Comment by Akshat55** [comment]
Hey @anemonetea & @r2-codes, have you tried following the example on [storybook](https://angular.carbondesignsystem.com/?path=/story/components-checkbox--with-reactive-forms)? 

In the demo, we use reactive form & enable/disable checkbox.

**Comment by r2-codes** [comment]
Hey @Akshat55 in my situation, if you are on that tab where the checkbox its is, I can toggle it, its perfect. But when I leave the checkbox on disable state, and return back to the checkbox with the disable state that is the moment when the error occurs. As I understand, when the component is initialized if has disable state there is the problem.
