### ISSUE TITLE
RangeError appears if ibm-dropdown-list has all disabled items

### ISSUE THREAD

**Issue by LomakoDasha** [carbon-design-system/carbon-components-angular#2283]
carbon-components: 10.56.0,
carbon-components-angular: 4.58.3

"RangeError: Maximum call stack size exceeded" while rendering <ibm-dropdown-list> that has only disabled items in the list  

![getNextElement-err-2](https://user-images.githubusercontent.com/42466442/194769489-a9437eca-49f9-470b-a71e-f773ae06d1a5.png)
![getNextElement-err-3](https://user-images.githubusercontent.com/42466442/194769502-1df063d5-5bd7-41bc-8457-dc96a58fe8d0.png)

**Actual result**: RangeError appears in the DevTools Console

**Expected result**: this type of lists renders without any errors

**Comment by Akshat55** [comment]
This issue was resolved in 4.73.1 - See PR  https://github.com/carbon-design-system/carbon-components-angular/pull/2524
