### ISSUE TITLE
Inconsistent time picker styling

### ISSUE THREAD

**Issue by miqh** [carbon-design-system/carbon-components-angular#2290]
## Detailed description

The Angular time picker implementation has aesthetic issues which I believe is due to the fact the `ibm-timepicker` component element doesn't include the `bx--form-item` CSS class.

## Steps to reproduce the issue

Visit:
* https://v7-react.carbondesignsystem.com/?path=/story/components-timepicker--default (v10)
* https://angular.carbondesignsystem.com/?path=/story/components-time-picker--simple (v10)

## Additional information
React implementation:
![image](https://user-images.githubusercontent.com/43751307/196014858-73e3dffb-4913-4503-ad14-4cca6c52f913.png)
Angular implementation:
![image](https://user-images.githubusercontent.com/43751307/196014843-796d439d-0645-4391-aaef-069245a91777.png)

**Comment by Akshat55** [comment]
Thanks for pointing this out @miqh!

From my understanding, this can be solved by adding `bx--form-item` class to the host.

My assumption is, developers have been wrapping this component with `div.bx--form-item`. Wrapping `.bx--form-item` within a `.bx--form-item` doesn't seem to be an issue, so we can move forward with adding the class to the host.
