### ISSUE TITLE
Missing md size in modals

### ISSUE THREAD

**Issue by PabloAznarez** [carbon-design-system/carbon-components-angular#2293]
In react version modal have this **"md"** size , but not in angular version , only have **"xs" | "sm" | "lg"**.

Regards.

**Comment by Akshat55** [comment]
This feature has been added in carbon-components-angular@next (v11). But I guess it should be back ported as well 🤔 There were many unreported breaking changes in regards to `size`, so will have to tread carefully here. Thought I don't think this should be that big of an issue to add.
