### ISSUE TITLE
Datefields needs ability to have helper text

### ISSUE THREAD

**Issue by gcate** [carbon-design-system/carbon-components-angular#2294]
My understanding is Carbon is moving from wanting the date format shown as a prompt to having date format shown as helper text.  
Currently the date fields components do not have helpertext as an attribute.
Can we add ability to have helpertext to single dates and date range components?

<img width="872" alt="image" src="https://user-images.githubusercontent.com/4819973/196274975-c0309849-ac36-4cde-a406-956211197f7d.png">

**Comment by Akshat55** [comment]
Hey @gcate,

I've taken a look at carbon react v10 & v11 and I don't see these changes reflected in either versions. There are no helper text prop for date picker component in code or [storybook](https://react.carbondesignsystem.com/?path=/story/components-datepicker--playground). 

> My understanding is Carbon is moving from wanting the date format shown as a prompt to having date format shown as helper text.

Could you please tell me how you came to this conclusion? I haven't been informed on this decision or or point me in the direction of the Carbon designer that have advocated for this? I would just like to confirm this with the Carbon team before making any changes 😄 

You can even port this in [#carbon-react](https://ibm-cognitive-engage.slack.com/archives/C2K6RFJ1G) to get feedback from a designer working on Carbon.

**Comment by gcate** [comment]
HI @Akshat55 I will check and get you someone to verify with. :)

**Comment by Akshat55** [comment]
Thanks!

**Comment by Akshat55** [comment]
Thanks for getting back to me on this! One thing to note is that the link you sent is for Carbon v11, same changes aren't stated in [Carbon v10](https://v10.carbondesignsystem.com/components/date-picker/usage/#main-elements) as of date. Does you team plan on upgrading to Carbon 11 (CCA v5)?


Change currently hasn't been applied in CCA v5, but will be available soon! 😄

**Comment by gcate** [comment]
I don't think our team will be upgrading in the near future.

**Comment by Akshat55** [comment]
Hi @gcate, my apologies I just noticed that helperText is an property in React, it just isn't listed in the storybook. I'll have a PR to add this to v10 shortly.

**Comment by gcate** [comment]
Thank you @Akshat55 !!
