### ISSUE TITLE
Recommendation: Versioning Synchronization

### ISSUE THREAD

**Issue by HaidarZ** [carbon-design-system/carbon-components-angular#2363]
### Recommendation
Sync the main version number with the original carbon-design-system main version.
i.e. let's say that the current latest version of carbon is v11.18.0 
We can take the v11 from it and keep the Minor and Patch for the current project.
So it could be v11.1.2 for the current project, it doesn't matter.

 ### Purpose
Keep aligned with the design-system release channel since the current used one is confusing.

**Comment by Akshat55** [comment]
Apologies for the late reply, but after discussing this with the team. We have decided to NOT synchronize with Carbon versioning. We came to this conclusion taking in to account the current versions of carbon-design-system/carbon (v1 with @carbon/react), carbon-design-system/vue (Current versions are v2/v3@next).


Majority were the reasons stated in the comment above. That being said, we will look into improving documentations to make it easier for Carbon angular consumers to differentiate the carbon versions with our own versions.
