### ISSUE TITLE
[tabs]: tab focus bordering on non actionable object

### ISSUE THREAD

**Issue by Sakshi-Shah2** [carbon-design-system/carbon-components-angular#2462]
## Detailed description

> The object that has no actionable component like a sorting header, link, or button should not have tab focus. 

> The issue seems to be related to ibm-tab component, they have tab focus even if there is no actionable object like a button or link. 

## Steps to reproduce the issue

1. Go to the data tables of the dashboard builder/card builder or any page where ibm-tabs are used with no actionable links/buttons. 
2. Click on the tab key.
3. Notice the focus borders.
4. An unusual border at the top of the table is seen, even if it has no actionable link there.
<img width="1728" alt="Screenshot 2023-02-21 at 6 44 30 PM" src="https://user-images.githubusercontent.com/123744004/220354906-c58e495a-e1ac-4696-8510-c692b69f0c88.png">

<img width="1676" alt="Screenshot 2023-02-21 at 8 02 16 PM" src="https://user-images.githubusercontent.com/123744004/220373381-6102774d-96b6-403d-9c4b-61e9f1e0f792.png">

## Additional information

* Screenshots or code
The object that has no actionable component like a sorting header, link, or button should not have tab focus. 

https://user-images.githubusercontent.com/123744004/220374709-5ee8df07-568c-4c6e-a870-2693743d69c1.mov

https://user-images.githubusercontent.com/123744004/220372860-19418a3a-3650-4d76-a455-837809d9568d.mov

_Here as seen in the above image, ibm-tab leads to the tab focus on the data table at the top (blue border as seen at the top) even if it doesn't have any link or actionable object on click._

**Comment by Akshat55** [comment]
@Sakshi-Shah2 You can manually update the tabIndex property, please see: 

https://github.com/carbon-design-system/carbon-components-angular/blob/f624f794cade468ade546c241013c6450ff4511b/src/tabs/tab.component.ts#L106

```html
			<ibm-tabs [followFocus]="followFocus" [isNavigation]="isNavigation" [cacheActive]="cacheActive">
				<ibm-tab heading="one" tabIndex="-1">Tab Content 1</ibm-tab>
				<ibm-tab heading="two" tabIndex="-1">Tab Content 2</ibm-tab>
				<ibm-tab heading="three" tabIndex="-1">Tab Content 3</ibm-tab>
				<ibm-tab heading="four" disabled="true">Tab Content 4</ibm-tab>
			</ibm-tabs>
```

You can also set `isNavigation` to true to set tabIndex of all tabs to -1/null (removing the property).
