### ISSUE TITLE
[data table]: Data table tab focus border

### ISSUE THREAD

**Issue by Sakshi-Shah2** [carbon-design-system/carbon-components-angular#2469]
## Detailed description

> The data tables have tab focus bordering for FF in windows, which is not reproducible for chrome/firefox in MacOs. 

> The issue is specific to FF on Windows.

>The non-actionable components like the data table should not come under focus bordering. And if we keep the tab focus for the whole data table (for consistent design among platforms) it should not get truncated. (the border is getting truncated is also specific to FF)

## Steps to reproduce the issue

1. Open any of the data tables under dashboard builder/card builder (specific to FF on windows)
2. Click on the tab key.
3. Notice the focus borders.

<img width="1728" alt="Screenshot 2023-03-02 at 12 07 33 AM" src="https://user-images.githubusercontent.com/123744004/222233960-dc7b9265-614d-4187-808d-07d44b22a99e.png">

## Additional information

> Recording for tab focus working - FF on Windows  

https://user-images.githubusercontent.com/123744004/222226940-78046290-a966-4dbb-81b3-8febab940463.mp4

> Recording for tab focus working - FF on MacOS

https://user-images.githubusercontent.com/123744004/222229459-49fcc9f0-5054-494d-ad2e-27a3718bb96f.mov

> Recording for tab focus working - Chrome on MacOS

https://user-images.githubusercontent.com/123744004/222229636-1deb4e3f-7418-4732-a0d4-44d96aacc31a.mov

> Difference among them in tab focus order is as follows

On Windows (FF)

1. Active tab
2. Tab Header 
3. Button - Actionable object
4. Data table
5. Actionable column header in the data table 
6. Pagination

On Mac (FF/chrome)

1. Active tab
2. Tab Header 
3. Button - Actionable object
4. Actionable column header in the data table 
5. Pagination

> Additional Information: The focus borders get truncated - an issue specific to FF for windows as well as mac.

**Comment by Akshat55** [comment]
Please check the container of the table to see if it does not have a tabIndex property set to 0 or greater.

**Comment by Sakshi-Shah2** [comment]
@Akshat55, attaching the screenshot for the table container - tab index property is not used for ibm-table

<img width="972" alt="Screenshot 2023-04-03 at 12 26 42 PM" src="https://user-images.githubusercontent.com/123744004/229434055-3cf9db5c-5d63-49be-8470-c651bb1c1f96.png">

**Comment by Akshat55** [comment]
Code sandbox reference with `interactive content`.

**Comment by Akshat55** [comment]
Closing in favor of #2462
