### ISSUE TITLE
Adding unique columns/rows id for "sc-table" components

### ISSUE THREAD

**Issue by yhs2** [carbon-design-system/carbon-components-angular#2474]
## Detailed description

> Describe in detail the issue you're having.
 my team is working on a development task and we need access to ids. The Component I am working on is "sc-table" and I would like to add unique ids to each rows / columns. Is there way to assign these attributes? Below is the sample code and the location I want to add those Ids. Thank you for your time

> Is this issue related to a specific component?
"sc-table"

> What did you expect to happen? What happened instead? What would you like to see changed?
unique ids for each column and rows of that table, now there is no id attribute for td / tr elements in "sc-table" component

> What browser are you working in?
Chrome

## Additional information

![sc-table1 (1)](https://user-images.githubusercontent.com/89870747/223225255-e82967ee-3fae-435c-9f52-2af354082e00.PNG)

**Comment by Akshat55** [comment]
Closing this issue, sc-table is deprecated and it is not part of carbon-components-angular.
