### ISSUE TITLE
[tooltip]: Tooltip description box should not get truncated

### ISSUE THREAD

**Issue by Sakshi-Shah2** [carbon-design-system/carbon-components-angular#2476]
## Detailed description

> Tooltip description box gets truncated due to the side navbar or top navbar. 

> This is an enhancement request for the general issue faced for the tooltip description box. 

> This issue is specific to the tooltip (description box).

> Tooltip description box should be positioned or sized in a way that it or the information inside it does not get truncated. Instead saw the tooltip component getting truncated (which happens for all the different tooltip directions) 

## Steps to reproduce the issue

1. Go to any tooltip near to navbar or any other component 
2. click on it - and check the description box (with more than 33-35 characters in the description).
3. Check the truncation. 

<img width="1387" alt="Screenshot 2023-03-14 at 7 07 45 PM" src="https://user-images.githubusercontent.com/123744004/225018723-f48fe203-e12c-459b-8e3b-a23ef5f5bc53.png">

_Above Screenshot is from IBM Supply Chain Intelligence Suite > Card Builder > My Cards > A Text card with short title or no title._

## Additional information

* Screenshots or code
Truncation instances on all four different directions.

<img width="780" alt="Screenshot 2023-03-14 at 7 15 17 PM" src="https://user-images.githubusercontent.com/123744004/225021569-e8321305-eb40-46bb-8e8c-a776a8bfb1b1.png">
<img width="780" alt="Screenshot 2023-03-14 at 7 15 28 PM" src="https://user-images.githubusercontent.com/123744004/225021582-0f67256f-1d9d-4b06-8009-04c41d8e2906.png">
<img width="780" alt="Screenshot 2023-03-14 at 7 15 40 PM" src="https://user-images.githubusercontent.com/123744004/225021589-08e9ebdd-320a-45e7-a371-60eca96dc57b.png">
<img width="780" alt="Screenshot 2023-03-14 at 7 15 53 PM" src="https://user-images.githubusercontent.com/123744004/225021594-342dc966-efb2-4628-8a2e-6523b75e5fac.png">

**Comment by Akshat55** [comment]
That's expected, the shell has a higher z-index (8000) compared to tooltip (6000).

Have you tried increasing the z-index of the tooltip?

**Comment by sakshi-shah14** [comment]
@Akshat55 yes, tried increasing tab-index of the tooltip in range from (8000-10000) but there was no change.
<img width="1728" alt="Screenshot 2023-03-18 at 12 32 29 AM" src="https://user-images.githubusercontent.com/94908338/227505426-7cba49f8-806c-43b5-bfd5-f76e6b90576c.png">
<img width="1728" alt="Screenshot 2023-03-18 at 12 36 00 AM" src="https://user-images.githubusercontent.com/94908338/227505441-fa5748a0-093c-49ab-bc67-4968f121d4b8.png">
<img width="1728" alt="Screenshot 2023-03-24 at 4 33 52 PM" src="https://user-images.githubusercontent.com/94908338/227505489-93f37597-ae12-4d8f-b8d5-38360cc53c7d.png">

**Comment by sakshi-shah14** [comment]
@Akshat55 Tried position style : relative 

<img width="1390" alt="Screenshot 2023-03-24 at 7 46 35 PM" src="https://user-images.githubusercontent.com/94908338/227548269-f869b435-bf33-43db-aed4-9e8c892397bd.png">

**Comment by Sakshi-Shah2** [comment]
@Akshat55, will require a better workaround for this issue, other than setting the position style for ibm-placeholder component the value of relative.
cc: @yinglejia

**Comment by Akshat55** [comment]
@sakshi-shah2, you will need to change the designs. There isn't much that we can do on our end since the iframe is a separate document. You cannot have content overflow out of an iframe as it is considered a security issue.

**Comment by Akshat55** [comment]
Closing this issue for now as there is no possible fix on our end.

Possible solutions:
1. Change the designs - This may be difficult & more work, but based on the shell implementation and the software design, this is the best solution imo. 
2. Set `ibm-placeholder` position style to be relative. This changes carbon styling so I do not recommend you choose this option.
