### ISSUE TITLE
carbon date picker components not supporting minDate and maxDate for angular

### ISSUE THREAD

**Issue by MJRakshit** [carbon-design-system/carbon-components-angular#2496]
Date picker components not supporting minDate and maxDate Validation for single date picker.
i have created a simple date picker example in two way. 
1st way

<ibm-date-picker class="example-full-width"
		formControlName="productRegisterDate"
		invalidText="Invalid date format"
		id="vr-datepicker"
                invalidText="Invalid Date Format"
                dateFormat= "M-d-Y"
                [maxDate]="04/20/2022">
</ibm-date-picker>

2nd way 

<ibm-date-picker class="example-full-width"
		formControlName="productRegisterDate"
		invalidText="Invalid date format"
		id="vr-datepicker"
                invalidText="Invalid Date Format"
                dateFormat= "M-d-Y"
                maxDate="04/20/2022">
</ibm-date-picker>
 
which one is the correct way to do this validation

**Comment by Akshat55** [comment]
Hey @MJRakshit,

You can add a min/max date value to the date picker using the following code:


### Template (*.component.html):
In the template, you can see I've binded the flatpickrOptions object.
```html
<ibm-date-picker
  class="example-full-width"
  invalidText="Invalid date format"
  id="vr-datepicker"
  invalidText="Invalid Date Format"
  [flatpickrOptions]="flatPickrOptions">
</ibm-date-picker>
```

### Code (*.component.ts):
```js
  flatPickrOptions = {
    minDate: new Date(),
    maxDate: new Date(2023, 4, 3)
  };
```

Additionally, you can take a look at this code sandbox example: 
https://codesandbox.io/s/frosty-lamarr-sie17r?file=/src/app/app.component.ts:188-274
