### ISSUE TITLE
popover of tooltip for button in data table toolbar is hidden

### ISSUE THREAD

**Issue by lionriver** [carbon-design-system/carbon-components-angular#2517]
## Detailed description

> Describe in detail the issue you're having.
In carbon-components-angular@next,  put a button with tooltip in table toolbar, but the tooltip is not visible.
It seems the overflow property was set with hidden.

I have found the root cause for this issue.
`.cds--batch-actions ~ .cds--toolbar-content {
    clip-path: polygon(0 0, 100% 0, 100% 100%, 0 100%);
}`

there is clip-path defined for the batch actions area. It makes popover outside of the defined clip-path invisible. If unset the clip-path, the popover can be shown.

Then I found another issue. Tooltip for buttons in toolbar actions area shows text in one line overflown without wrapping. I didn't resolve this yet. So for, the popover blocks seems transparent somehow.

> Is this a feature request (new component, new icon), a bug, or a general issue?
No
> Is this issue related to a specific component?
Tooltip, Table
> What did you expect to happen? What happened instead? What would you like to see changed?
I expect to display tooltip popover when hover. But the tooltip popover is invisible.

> What browser are you working in?
Chrome
> What version of the Carbon Design System are you using?
    `"carbon-components": "10.58.3"`
    `"carbon-components-angular": "^5.7.4"`

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue
`<cds-table-toolbar [model]="model" #toolbar>
        <cds-table-toolbar-content>
            <button ibmButton="primary" size="sm" [tabindex]="toolbar.selected ? -1 : 0">
                <cds-tooltip [isOpen]="true" [caret]="true" [align]="'bottom'"
                    [description]="templateTooltipDisable">
                    <span>
                        Train system
                    </span>
                    <ng-template #templateTooltipDisable let-tooltip="tooltip">
                        In training
                    </ng-template>
                </cds-tooltip>
            </button>
        </cds-table-toolbar-content>
    </cds-table-toolbar>`

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by Akshat55** [comment]
@lionriver I believe we had discussed this on slack - You will need to raise an issue in the main [carbon monorepo](https://github.com/carbon-design-system/carbon). Unsetting the clip path will raise other issues so better to handle it in the root with carbon design team. They may be able to provide you with design alternatives & fixes.

Feel free to reference this issue. Closing for now.
