### ISSUE TITLE
Angular 16 standalone app support

### ISSUE THREAD

**Issue by maicongodinho** [carbon-design-system/carbon-components-angular#2548]
## Detailed description

> Describe in detail the issue you're having.

The issue I am facing is related to the lack of Angular 16 support, which prevents me from utilizing the latest features of Angular for creating standalone components. Specifically, I have noticed that the carbon modules are not functioning correctly with these components.

![image](https://user-images.githubusercontent.com/94566751/236320728-5decbbf7-ee85-4ef5-acb1-b6aed68d0766.png)

[Codesandbox](https://codesandbox.io/p/github/maicongodinho/carbon-ng-16-support)

**Comment by Akshat55** [comment]
Closing this PR @maicongodinho since CCA v5 is out and support for Angular 16 is available.
