### ISSUE TITLE
Overflow menu position is not aligned at the correct place

### ISSUE THREAD

**Issue by AmirHussain93** [carbon-design-system/carbon-components-angular#2609]
## Detailed description
I am using **ibm-overflow** menu inside **ibm-table** component. I wanted this overflow menu to be positioned below hamburger icon for every row. I am not able to figure out why the menu is going 3-4 rows above from the exact position. Could you please look into this ?

> Is this a feature request (new component, new icon), a bug, or a general issue?
Its a bug

> Is this issue related to a specific component?
Over flow menu: **ibm-overflow-menu**

> What did you expect to happen? What happened instead? What would you like to see changed?
Overflow Menu should  be aligned properly with every row of the table

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
 "carbon-components": "^10.58.3",
 "carbon-components-angular": "^4.74.0",

## Additional information
This issue is not only when overflow menu is used inside ibm-table component but individually as well. I am sharing two different screenshots below

* Screenshots or code
<img width="303" alt="Screenshot 2023-06-21 at 11 15 34 AM" src="https://github.com/carbon-design-system/carbon-components-angular/assets/27803197/a0fa781e-5f74-462f-95ff-27d67f0c887d">

<img width="649" alt="image" src="https://github.com/carbon-design-system/carbon-components-angular/assets/27803197/8e1e0500-b435-4c51-a910-d181ac40e0ab">

**Comment by AmirHussain93** [comment]
@Akshat55 could you please look into this ASAP ? We have a demo coming up next week.

**Comment by Akshat55** [comment]
@AmirHussain93 - You're applying extra styling somewhere - take a look at this [story example](https://angular.carbondesignsystem.com/?path=/story/components-table--with-overflow-menu), you'll see that the position of the overflow menu is correct. You can view the exact code [here](https://github.com/carbon-design-system/carbon-components-angular/blob/master/src/table/stories/app-overflow-table.component.ts).

I recommend checking the position of the target is `relative`.

**Comment by Akshat55** [comment]
Closing issue since this issue is on user's end. Storybook demo clearly shows the menu working. Please check for `position` styling that wraps the table component.

**Comment by AmirHussain93** [comment]
@Akshat55 Thanks for the reply. 

I was able to fix this.
