### ISSUE TITLE
Vunerable jQUERY reported on the docs

### ISSUE THREAD

**Issue by AlvinChacko** [carbon-design-system/carbon-components-angular#2661]
## Detailed description

> Describe in detail the issue you're having.

I noticed the OWASP dependency checker reported vulnerabilities in the jQuery version 2.1.1. I dont see the issue reported earlier, is this something or considered false positives. Can I avoid the docs in the package?

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

carbon-components-angular

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

    "carbon-components": "^10.58.3",
    "carbon-components-angular": "^4.75.3",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

**Comment by Akshat55** [comment]
Hey @AlvinChacko, we do not have Jquery as part of our dependencies. I've verified this in v4 package-lock.json. What SAST did you use to determine this vulnerability?

**Comment by AlvinChacko** [comment]
I used the OWASP dependency checker. Here is the screenshot of it:
![Screen Shot 2023-07-19 at 5 58 42 PM](https://github.com/carbon-design-system/carbon-components-angular/assets/40772617/9a0883b4-3632-49d8-9299-30f03f6294ca)
