### ISSUE TITLE
pagination controls text missing on window resize

### ISSUE THREAD

**Issue by oetlinge** [carbon-design-system/carbon-components-angular#2664]
## Detailed description

> Describe in detail the issue you're having.

When resizing the window and decreasing the page width, beyond a certain threshold, the pagination component changes from displaying all relevant information (i.e. items per page, total items count and page number) to just the next/prev page buttons. By comparison, when doing the same to the pagination component from the base carbon components, the number of currently displayed and total items is shown along with the next/prev page buttons.

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

Pagination Component

> What did you expect to happen? What happened instead? What would you like to see changed?

Expectation was for the count of items on the current page and total items count to be displayed as is done by non-Angular framework. Actual behaviour was that only the next/prev page buttons were displayed. Angular framework's pagination component should be consistent across frameworks.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

carbon-components@10.58.5
carbon-components-angular@4.73.1

**Issue is reproducible in carbon components angular storybook as well.**

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Supply Chain Intelligence Suite

## Steps to reproduce the issue

[Codesandbox](https://codesandbox.io/s/carbon-components-angular-forked-8krh5k?file=/src/app/app.component.ts)

1. Create a page with a pagination component. Specify all the default options for the component.
2. Grab the left or right edge of the window and begin dragging to decrease the width.
3. Beyond a certain threshold, the pagination component is reduced to next/prev page buttons and no text.

### Carbon Components Angular Pagination component when window width decreased
![image](https://github.com/carbon-design-system/carbon-components-angular/assets/59981506/fc86aaff-eaaf-4645-bd95-5c521d344107)

### Carbon Components Pagination component when window width decreased
![image](https://github.com/carbon-design-system/carbon-components-angular/assets/59981506/c34f4555-5c1a-4bea-a1d3-00e5732debf8)

**Comment by Akshat55** [comment]
Reopening since we need to make this change in v10 as well

**Comment by Akshat55** [comment]
Thanks @kush-savani for taking this on!

Closing PR, it's been resolved in both v4 and v5!
