### ISSUE TITLE
How can i set a default theme?

### ISSUE THREAD

**Issue by seriouz** [carbon-design-system/carbon-components-angular#2668]
How is it possible in carbon-components-angular to set the default theme for the whole application to dark or g100 like for React?
https://carbondesignsystem.com/guidelines/themes/code
I did not find any documentation on how the change the apps default theme.

**Comment by Akshat55** [comment]
Here is a working code sandbox that shows you how to set default theme OR switch application theme:

https://codesandbox.io/p/sandbox/angular-angular?file=%2Fpackage.json%3A25%2C23

Files to look at are:
* styles.scss
* app.component.ts

**Comment by seriouz** [comment]
Thanks for the response, but I think you gave the wrong sandbox link :D

**Comment by Akshat55** [comment]
Whoops! Sorry about that, have a lot of sandboxes open 😆 

Here is the link: https://codesandbox.io/p/sandbox/cocky-dust-t2d2cw?file=%2Fpackage.json%3A25%2C23

**Comment by seriouz** [comment]
I've tested it directly in my app and it works like a charm! Thank you!

**Comment by fronbasal** [comment]
@flisijn Struggling with the same thing - how can we override design tokens?

**Comment by Sparker0i** [comment]
> Whoops! Sorry about that, have a lot of sandboxes open 😆
> 
> Here is the link: https://codesandbox.io/p/sandbox/cocky-dust-t2d2cw?file=%2Fpackage.json%3A25%2C23

Hey @Akshat55 , looks like the sandboxes aren't working anymore. 
If you still have an example around, would you mind sharing another sandbox of the same?
