### ISSUE TITLE
[Bug]: cds-number component + - buttons do not work after entering value manually in the input

### ISSUE THREAD

**Issue by fuksoboy** [carbon-design-system/carbon-components-angular#2672]
Using carbon-components-angular v 5.14.0.
In cds-number component, when I first enter value manually in the input then + - buttons do not work.

**Comment by rulvalery** [comment]
@Akshat55 Hi. I have the same problem in carbon-components-angular v4.75.6. Do you support old versions and could you fix this problem at least for version carbon-components-angular v4.75.6 ?
