### ISSUE TITLE
Storybook: code tab is not loading code

### ISSUE THREAD

**Issue by adhikln** [carbon-design-system/carbon-components-angular#2694]
@storybook/addon-storysource is not working, stuck on loading source 
![image](https://github.com/carbon-design-system/carbon-components-angular/assets/121623988/53212d39-6585-4706-9437-a68b274e4f9a)

**Comment by Akshat55** [comment]
I'm assuming you're viewing the storybook published on next branch. There is no `Code` tab on production [angular.carbondesignsystem.com](https://angular.carbondesignsystem.com/?path=/story/getting-started--welcome).

In production storybook, you can view the `docs` page for each component and view the code via clicking the  `show code`. See the example below: 

![image](https://github.com/carbon-design-system/carbon-components-angular/assets/38994122/8353b85b-e1c2-4647-aaba-43218c734bbb)
