### ISSUE TITLE
Sidenav issue when displayed together with Header

### ISSUE THREAD

**Issue by placzkowskim** [carbon-design-system/carbon-components-angular#2703]
When using sidenav together with header like is described in : 
https://angular.carbondesignsystem.com/?path=/story/components-ui-shell--together

Sidenav should be moved down by the height of the header if it is used together.

**Comment by Akshat55** [comment]
Won't fix, it would require some unnecessary logic where the side nav would have to check if header component exists. This would open a can of worms and we would then have to resolve issues for certain scenarios.

Simply add `margin-top: 3rem` to sidenav.
