### ISSUE TITLE
Multi Dropdown skeleton states is not enabled

### ISSUE THREAD

**Issue by rohit-sinha1989** [carbon-design-system/carbon-components-angular#2715]
## Detailed description

> Is this a feature request (new component, new icon), a bug, or a general issue?
   
A general issue/Bug

> Is this issue related to a specific component?

Multi Dropdown/Combobox

> What did you expect to happen? What happened instead? What would you like to see changed?

Skeleton should work on Multi Dropdown and Content (Selected/placeholder text) should not be shown when it is enabled.

> What browser are you working in?

Applies to ALL

> What version of the Carbon Design System are you using?

v5.14.11

## Steps to reproduce the issue

1. Create multi dropdown component, set placeholder or set an item to be selected, set skeleton value to true.

2. You will see the placeholder or value that is default selected and skeleton is not working

## Additional information

            <cds-dropdown label="Select" type="multi" value="value" (selected)="onClickOnMultiSelect($event)"
                      placeholder="Select Color" title='' [(ngModel)]="selectedPreferredColor"  [skeleton]="showDashboardSkeleton">
                      <cds-dropdown-list [items]="preferredColorList"  [listTpl]="dropdownColorList"></cds-dropdown-list>
            </cds-dropdown>

**Comment by Akshat55** [comment]
@ENate, this should be a good first issue. Placeholder isn't working for multidropdown & when it is enabled in single, it is showing the placeholder or default selected value. For this, you can probably just use attribute binding, so something like: 
```
[attr.placeholder]="skeleton ? placeholder: null"
```

![image](https://github.com/carbon-design-system/carbon-components-angular/assets/38994122/5f5567b1-08dc-4497-918b-47e7548dc966)

Multi dropdown uses the same component, so not sure why it isn't working there, may need to do some digging around in the component.

**Comment by ENate** [comment]
@Akshat55  It seems there is a fix for this  issue already?

**Comment by Akshat55** [comment]
Issue is still open, seems like @abiramcodes picked it up...

I've reopened this issue as the solution provided was not sufficient, feel free to contribute a fix. Hint, have a look at `getDisplayStringValue` function!

**Comment by abiramcodes** [comment]
Correct me if I am wrong, 
There should not be any placeholder value when the `skeleton value is set as true`. 

Question : 
Should the dropdown values also needs to be made as empty/null ?

**Comment by Akshat55** [comment]
Yes, you're right. The placeholder should not be displayed when skeleton value is true. In your previous PR, you set the value in ngOnInit, the issue with this is if they toggle skeleton again after the initial load. 

Instead, I would recommend using the `getDisplayStringValue` function and returning null when skeleton is active. So something like this:

```ts
	getDisplayStringValue(): Observable<string> {
		if (!this.view || this.skeleton) {
			return;
		}
		...
	}
```
