### ISSUE TITLE
ActionableNotification close button action.

### ISSUE THREAD

**Issue by placzkowskim** [carbon-design-system/carbon-components-angular#2724]
ActionableNotification close button action.

Hi I have created actionable notification like:

`    <cds-actionable-notification
        [notificationObj]="{
    inline: true,
    type: 'error',
    title: 'Error: Unable to procees your request this time.',
    actionsTemplate: customActionableTrigger,
    message: 'Please try again later',
    showClose:true,
    lowContrast: true,
}"
        (close)="onNotificationClose()"
    >
    </cds-actionable-notification>`

I need such default behaviour as close that component on 'x' click. 
My onNotificationClose() method is beeing properly invoked on 'x' click.
How can I achieve it ? 
Should I somehow register notification component created in template in NotificationService ? 
`NotificationDisplayService ` exposes `close()` method but it accepts ComponentRef. Does this mean that I should create that notification using ComponentResolverFactory ? Or there is some simple solution that I'm missing.

**Comment by nipun005** [comment]
Hi @placzkowskim, To implement such functionality- When the user will click on close icon of the actionable notification, Then your method which you written should invoke, Fix is required in actionable-notification file.
Please assign this issue to me, I will fix it and would raise PR.

**Comment by nipun005** [comment]
Hi @placzkowskim,  Below PR has been raised for above issue.
https://github.com/carbon-design-system/carbon-components-angular/pull/2727

After merging of this PR, On Click of X button of ActionableNotification, "onNotificationClose()" method will automaticaaly be invoked if you check with above code again that you used previously, and you would not be needed  to use any other approach like- ComponentResolverFactory or something.

**Comment by Akshat55** [comment]
Hi, if you would like to `close` the notification. I highly recommend using the notification service to dynamically render your component. The component will be dynamically removed on `x` click. We have quite a few examples of this in our storybook: 

https://angular.carbondesignsystem.com/?path=/story/components-notification--dynamic-inline
