### ISSUE TITLE
Context Menu component has the wrong module

### ISSUE THREAD

**Issue by lSilvani** [carbon-design-system/carbon-components-angular#2749]
Looking at Storybook, it seems the Context Menu component has the wrong import module. 
It says "ContextSwitcherModule", but it should be "ContextMenuModule"? 

<img width="589" alt="Screenshot 2024-01-09 at 13 11 14" src="https://github.com/carbon-design-system/carbon-components-angular/assets/116547024/5e2f3e50-80f5-4897-8d61-b1672aeadda8">

**Comment by Akshat55** [comment]
Thanks for reporting this @lSilvani! Would you like to contribute this fix? :) 

You would update the following line to the correct module and restart storybook (`npm run storybook`):

https://github.com/carbon-design-system/carbon-components-angular/blob/ebb57a98147b5d2f7a357c24feb2d97c075dbe15/src/context-menu/context-menu.component.ts#L15
