### ISSUE TITLE
Accordian does not work in latest Carbon v5 due to issues with @carbon/styles

### ISSUE THREAD

**Issue by abinovarghese** [carbon-design-system/carbon-components-angular#2757]
## Detailed description

I cannot seem to get the cds-accordion-item element to expand and collapse the content within the tag. I have found that the expanded property is set correctly, and the icon to indicate expanded ^ or collapsed v is changing, but the content within the tag is always displayed regardless if the accordian element is expanded or not.

it seems something changed between version 1.40.0 and 1.46.0 of the @carbon/styles package that broke the accordion functionality. If you use the latest version, 1.46.0, the content of cds-accordian-item is expanded all the time. @carbon/styles 1.40.0 behaves as expected.

## Steps to reproduce the issue

Try opening according module with latest carbon angular component and carbon styles version.

**Comment by Akshat55** [comment]
Observed this issue recently, will have a fix out soon. Sorry for the delay!
