### ISSUE TITLE
Date Picker Issues with Carbon v5

### ISSUE THREAD

**Issue by abinovarghese** [carbon-design-system/carbon-components-angular#2758]
## Detailed description

If you load the data picker with pre configured data ranges and click and the date picker and click outside the values in the date picker shown in UI gets reset but actual values still remain intact. 

Replicable even in https://angular.carbondesignsystem.com/?path=/story/components-date-picker--range

Also while loading and below console error is logged
![Screenshot 2024-01-13 223416](https://github.com/carbon-design-system/carbon-components-angular/assets/9087797/55ceec0f-ef38-46cf-9c84-990ce5763120)

**Comment by Akshat55** [comment]
We resolved this with PR https://github.com/carbon-design-system/carbon-components-angular/pull/2681. Please try updating to the latest version of carbon-components-angular. If you still see this issue, delete your node_modules and reinstall.

**Comment by Akshat55** [comment]
@abinovarghese Closing the issue, feel free to reopen or comment if you still run into this issue.
