### ISSUE TITLE
When could carbon-components-angular support angular 17?

### ISSUE THREAD

**Issue by zosmf-Mira** [carbon-design-system/carbon-components-angular#2760]
## Detailed description

> Recently we plan to set up a new angular project with Angular 17, however, we found that the support list of carbon-components-angular just to angular 16, could you kindly please tell us what is your support plan so that we could do balance it with our deliver schedule.  Thanks!

> Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by zosmf-Mira** [comment]
Thanks !

**Comment by marianSimonca** [comment]
Is this really fixed? As we have just started a project using Angular 17 (17.1.0 more precisely, but we've done tests with 17.0.0 as well and it didn't work) and we have lots of issues with importing styles and using carbon-components-angular.
Our tests with Angular 16 worked quick and easy.

Can you help us with a codesandbox or a simple guide how to make it work with Angular 17?

**Comment by eduardmarcinco** [comment]
This is a simple sandbox with a button using Angular 17 
https://codesandbox.io/p/devbox/dynamic-icons-forked-3d2xzs?file=%2Fsrc%2Fstyles.scss

If you have some issues I urge you to open separate issue with error msgs you see and ideally codesandboxes.

**Comment by zosmf-Mira** [comment]
Eduard,
Thanks a lot for your notice!
However, Eduard could you please let me edit it so that I can do experiment on it such as test whether <ibm-modal> tag work well on it?

--
Thanks.
 Mira Yuan (袁圆)
Software Engineer, China System Technology Lab.
IBM z/OS Management Facility marketplace<https://www.ibm.com/us-en/marketplace/zos-management-facility>
E-mail: ***@***.******@***.***>
Address: No.28, Zhong Guan Cun Software Park, No.8 Dong Bei Wang West Road, Hai Dian District, Beijing 100193, P.R.China



发件人: Eduard Marcinco ***@***.***>
日期: 星期四, 2024年2月1日 下午7:39
收件人: carbon-design-system/carbon-components-angular ***@***.***>
抄送: Yuan IH Yuan ***@***.***>, State change ***@***.***>
主题: [EXTERNAL] Re: [carbon-design-system/carbon-components-angular] When could carbon-components-angular support angular 17? (Issue #2760)
This is a simple sandbox with a button using Angular 17 https: //codesandbox. io/p/devbox/dynamic-icons-forked-3d2xzs?file=%2Fsrc%2Fstyles. scss If you have some issues I urge you to open separate issue with error msgs you see and ideally codesandboxes. 
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!1a-rqJY1AVJZEK8Ts6uuTYK8YXHdXhdu4EOQbmQzmXGm8ZyJgLw1Yn6JOqLWy4XtEfPJ7Bg-ua7HMC2P9LmEhP_NaKMVC9TeCVU-tfu_YTY02IIHneh7WESNLDZl-S_BFAiIY1CaoeSDVA$>
Report Suspicious <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!1a-rqJY1AVJZEK8Ts6uuTYK8YXHdXhdu4EOQbmQzmXGm8ZyJgLw1Yn6JOqLWy4XtEfPJ7Bg-ua7HMC2P9LmEhP_NaKMVC9TeCVU-tfu_YTY02IIHneh7WESNLDZl-S_BFAiIY1CaoeSDVA$>


ZjQcmQRYFpfptBannerEnd

This is a simple sandbox with a button using Angular 17
https://codesandbox.io/p/devbox/dynamic-icons-forked-3d2xzs?file=%2Fsrc%2Fstyles.scss<https://codesandbox.io/p/devbox/dynamic-icons-forked-3d2xzs?file=%2Fsrc%2Fstyles.scss>

If you have some issues I urge you to open separate issue with error msgs you see and ideally codesandboxes.

**Comment by eduardmarcinco** [comment]
Hi, modal works as well.
Please see this update code sandbox -> https://codesandbox.io/p/devbox/3d2xzs?file=%2Fsrc%2Fapp%2Fapp.component.html

Key things for using modal:
- import `ModalModule` and `PlaceholderModule` in your `AppModule`
- put `<cds-placeholder></cds-placeholder>` to your `AppComponent` template. Placeholder is used as a root component for modal.

![image](https://github.com/carbon-design-system/carbon-components-angular/assets/359643/f2479de4-a484-4cff-9a6a-d59d9878d063)

btw, if you want to edit the code sandbox, you need to fork it (top right corner).

**Comment by zosmf-Mira** [comment]
However, NotificationService did not work well, could you help address it?

import { ModalService, NotificationService, ActionableContent } from 'carbon-components-angular';

***@***.***

--
Thanks.
 Mira Yuan (袁圆)
Software Engineer, China System Technology Lab.
IBM z/OS Management Facility marketplace<https://www.ibm.com/us-en/marketplace/zos-management-facility>
E-mail: ***@***.******@***.***>
Address: No.28, Zhong Guan Cun Software Park, No.8 Dong Bei Wang West Road, Hai Dian District, Beijing 100193, P.R.China



发件人: Eduard Marcinco ***@***.***>
日期: 星期一, 2024年2月5日 下午4:58
收件人: carbon-design-system/carbon-components-angular ***@***.***>
抄送: Yuan IH Yuan ***@***.***>, State change ***@***.***>
主题: [EXTERNAL] Re: [carbon-design-system/carbon-components-angular] When could carbon-components-angular support angular 17? (Issue #2760)
Hi, modal works as well. Please see this update code sandbox -> https: //codesandbox. io/p/devbox/3d2xzs?file=%2Fsrc%2Fapp%2Fapp. component. html Key things for using modal: import ModalModule and PlaceholderModule in your AppModule put <cds-placeholder></cds-placeholder>
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!1a-rqJY1AVJZEK8Ts6uuTYK8YXHdXhdu4EOQbmQzmXGm8ZyJgLw1Yn6JOqLWy4XtEfPJ7Bg-ua7HMC2P9LmEhP8t6MMVS_Q-CVU-tfu_YTb3JEPy_5T8wXm_M37GJVeG2dKZicrHUMYpdQ$>
Report Suspicious <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!1a-rqJY1AVJZEK8Ts6uuTYK8YXHdXhdu4EOQbmQzmXGm8ZyJgLw1Yn6JOqLWy4XtEfPJ7Bg-ua7HMC2P9LmEhP8t6MMVS_Q-CVU-tfu_YTb3JEPy_5T8wXm_M37GJVeG2dKZicrHUMYpdQ$>


ZjQcmQRYFpfptBannerEnd

Hi, modal works as well.
Please see this update code sandbox -> https://codesandbox.io/p/devbox/3d2xzs?file=%2Fsrc%2Fapp%2Fapp.component.html<https://codesandbox.io/p/devbox/3d2xzs?file=%2Fsrc%2Fapp%2Fapp.component.html>

Key things for using modal:

  *   import ModalModule and PlaceholderModule in your AppModule
  *   put <cds-placeholder></cds-placeholder> to your AppComponent template. Placeholder is used as a root component for modal.

image.png (view on web)<https://github.com/carbon-design-system/carbon-components-angular/assets/359643/f2479de4-a484-4cff-9a6a-d59d9878d063>

btw, if you want to edit the code sandbox, you need to fork it (top right corner).

**Comment by eduardmarcinco** [comment]
What error do you see? It's hard to guess what might the problem.

But in general, you want to add `NotificationService` to `providers` array in your component.

See this snippet:

```typescript
import { NotificationService } from "carbon-components-angular";

@Component({
  selector: "app-some-component",
  templateUrl: "./some-component.component.html",
  styleUrls: ["./some-component.component.scss"],
  providers: [NotificationService],
})
export class SomeComponent {
  
  constructor(
    private notificationService: NotificationService,
  ) {}

}
```

**Comment by zosmf-Mira** [comment]
Yes, Eduard. As you said it works well when it is used in a component.
But I use it in a service instead of a component, as below
import { ModalService, NotificationService, ActionableContent } from 'carbon-components-angular';

@Injectable({
  providedIn: 'root'
})
export class MessageService {
constructor(
    …
private notificationService: NotificationService
  ) { }
…
}

And this service is used by a component,

import { MessageService } from '../_services/message.service';
@Component({
  selector: 'app-message-in-modal',
  templateUrl: './message-in-modal.component.html',
  styleUrl: './message-in-modal.component.css'
})

export class MessageInModalComponent extends BaseModal implements OnInit {
constructor(
    public _messageService: MessageService
    ) {
    super();
   }
…
}

So my question is , how can I make it recognized by a service instead of component?
--
Thanks.
 Mira Yuan (袁圆)
Software Engineer, China System Technology Lab.
IBM z/OS Management Facility marketplace<https://www.ibm.com/us-en/marketplace/zos-management-facility>
E-mail: ***@***.******@***.***>
Address: No.28, Zhong Guan Cun Software Park, No.8 Dong Bei Wang West Road, Hai Dian District, Beijing 100193, P.R.China



发件人: Eduard Marcinco ***@***.***>
日期: 星期二, 2024年2月6日 下午6:58
收件人: carbon-design-system/carbon-components-angular ***@***.***>
抄送: Yuan IH Yuan ***@***.***>, State change ***@***.***>
主题: [EXTERNAL] Re: [carbon-design-system/carbon-components-angular] When could carbon-components-angular support angular 17? (Issue #2760)
What error do you see? It's hard to guess what might the problem. But in general, you want to add NotificationService to providers array in your component. See this snippet: import { NotificationService } from "carbon-components-angular"; @Component({
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!1a-rqJY1AVJZEK8Ts6uuTYK8YXHdXhdu4EOQbmQzmXGm8ZyJgLw1Yn6JOqLWy4XtEfPJ7Bg-ua7HMC2P9LmEhP7NCAI1SnReCVU-tfu_YTb02X66CZ2Rz41LUkulAU75D5AlJmw6O-Ruhg$>
Report Suspicious <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!1a-rqJY1AVJZEK8Ts6uuTYK8YXHdXhdu4EOQbmQzmXGm8ZyJgLw1Yn6JOqLWy4XtEfPJ7Bg-ua7HMC2P9LmEhP7NCAI1SnReCVU-tfu_YTb02X66CZ2Rz41LUkulAU75D5AlJmw6O-Ruhg$>


ZjQcmQRYFpfptBannerEnd

What error do you see? It's hard to guess what might the problem.

But in general, you want to add NotificationService to providers array in your component.

See this snippet:

import { NotificationService } from "carbon-components-angular";



@Component({

  selector: "app-some-component",

  templateUrl: "./some-component.component.html",

  styleUrls: ["./some-component.component.scss"],

  providers: [NotificationService],

})

export class SomeComponent {



  constructor(

    private notificationService: NotificationService,

  ) {}



}

―

**Comment by eduardmarcinco** [comment]
It is possible to use it in service as well.
Please see this codesandbox -> GlobalNotificationService
https://codesandbox.io/p/devbox/twilight-meadow-jmq38j?file=%2Fsrc%2Fapp%2Fglobal-notification.service.ts%3A11%2C1

**Comment by zosmf-Mira** [comment]
Eduard,
Thanks a lot! It works well now.

--
Thanks.
 Mira Yuan (袁圆)
Software Engineer, China System Technology Lab.
IBM z/OS Management Facility marketplace<https://www.ibm.com/us-en/marketplace/zos-management-facility>
E-mail: ***@***.******@***.***>
Address: No.28, Zhong Guan Cun Software Park, No.8 Dong Bei Wang West Road, Hai Dian District, Beijing 100193, P.R.China



发件人: Eduard Marcinco ***@***.***>
日期: 星期三, 2024年2月7日 下午3:01
收件人: carbon-design-system/carbon-components-angular ***@***.***>
抄送: Yuan IH Yuan ***@***.***>, State change ***@***.***>
主题: [EXTERNAL] Re: [carbon-design-system/carbon-components-angular] When could carbon-components-angular support angular 17? (Issue #2760)
It is possible to use it in service as well. Please see this codesandbox -> GlobalNotificationService https: //codesandbox. io/p/devbox/twilight-meadow-jmq38j?file=%2Fsrc%2Fapp%2Fglobal-notification. service. ts%3A11%2C1 — Reply to this
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!1a-rqJY1AVJZEK8Ts6uuTYK8YXHdXhdu4EOQbmQzmXGm8ZyJgLw1Yn6JOqLWy4XtEfPJ7Bg-ua7HMC2P9LmEhN_NyMOVyhS-CVU-tfu_YTYqEWb4BicgCwguHjBNrd8iQIeeREnqQidTlg$>
Report Suspicious <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!1a-rqJY1AVJZEK8Ts6uuTYK8YXHdXhdu4EOQbmQzmXGm8ZyJgLw1Yn6JOqLWy4XtEfPJ7Bg-ua7HMC2P9LmEhN_NyMOVyhS-CVU-tfu_YTYqEWb4BicgCwguHjBNrd8iQIeeREnqQidTlg$>


ZjQcmQRYFpfptBannerEnd

It is possible to use it in service as well.
Please see this codesandbox -> GlobalNotificationService
https://codesandbox.io/p/devbox/twilight-meadow-jmq38j?file=%2Fsrc%2Fapp%2Fglobal-notification.service.ts%3A11%2C1<https://codesandbox.io/p/devbox/twilight-meadow-jmq38j?file=%2Fsrc%2Fapp%2Fglobal-notification.service.ts%3A11%2C1>
