### ISSUE TITLE
NullInjectorError: No provider for ViewContainerRef

### ISSUE THREAD

**Issue by frankiereyes** [carbon-design-system/carbon-components-angular#2763]
## Detailed description

Versions 5.7.7 and later are showing 'no provider for ViewContainerRef' error when attempting to display a notification or toast using the `NotificationService`.  This error is not present in version 5.7.6 and is able to display notifications and toasts.
```
main.ts:6 ERROR NullInjectorError: R3InjectorError(AppModule)[NotificationService -> ViewContainerRef -> ViewContainerRef]: 
  NullInjectorError: No provider for ViewContainerRef!
    at NullInjector.get (core.mjs:8890:27)
    at R3Injector.get (core.mjs:9334:33)
    at R3Injector.get (core.mjs:9334:33)
    at injectInjectorOnly (core.mjs:842:40)
    at Module.ɵɵinject (core.mjs:848:60)
    at Object.NotificationService_Factory [as factory] (carbon-components-angular-notification.mjs:22:102)
    at core.mjs:9454:43
    at runInInjectorProfilerContext (core.mjs:798:9)
    at R3Injector.hydrate (core.mjs:9453:17)
    at R3Injector.get (core.mjs:9323:33)
```

## Steps to reproduce the issue

The attached sandbox link displays the error when attempting to display a notification in `app.component.ts`.
[Codesandbox](https://codesandbox.io/p/sandbox/carbon-components-angular-5-7-7-vqq4mv)

1. Open the sandbox dev console and see the null injector error
2. Install `carbon-components-angular@5.7.6` and rerun
3. Verify the notification is displayed as expected

## Additional information
The same error was identified in [issue 2716](https://github.com/carbon-design-system/carbon-components-angular/issues/2716), however it was closed as being related to `@ngrx` v14.3 or higher. This sandbox does not have any reference to `@ngrx` and is still exhibiting the same error.

**Comment by Akshat55** [comment]
@frankiereyes You need to pass `NotificationService` as a provider in your `@component({...})` decorator. See the following example:

https://github.com/carbon-design-system/carbon-components-angular/blob/ebb57a98147b5d2f7a357c24feb2d97c075dbe15/src/notification/stories/dynamic-actionable.component.ts#L11

**Comment by Akshat55** [comment]
Also, I recommend you update to carbon-components-angular@5.14.0+ - we had an issue with matching tags in our release unfortunately, so v5 stable starts after 5,14,0.

Feel free to reopen the issue if needed!

**Comment by frankiereyes** [comment]
@Akshat55 Thanks for pointing out the documentation story! Specifying `providers` works nicely when used inside a component. Are there any documented examples for using `NotificationService.showNotification`  from within another service? I'm getting the same error when attempting this approach:
https://codesandbox.io/p/devbox/long-cherry-qmhws6?file=%2Fsrc%2Fapp%2Fapp.service.ts%3A20%2C1

**Comment by Akshat55** [comment]
@frankiereyes Here is a working code sandbox I had created a while back for this scenario:

https://codesandbox.io/p/devbox/twilight-meadow-jmq38j

In short, angular injects `ViewContainerRef` in components by default and not services. Hence. we have to manually pass `ViewContainerRef` to the global notification service. then pass it as a parameter when creating the NotificationService.

**Comment by frankiereyes** [comment]
@Akshat55 Thanks for the working example... this was exactly the info I was looking for!

**Comment by sjbeatle** [comment]
> [@frankiereyes](https://github.com/frankiereyes) Here is a working code sandbox I had created a while back for this scenario:
> 
> https://codesandbox.io/p/devbox/twilight-meadow-jmq38j
> 
> In short, angular injects `ViewContainerRef` in components by default and not services. Hence. we have to manually pass `ViewContainerRef` to the global notification service. then pass it as a parameter when creating the NotificationService.

This link no longer seems to work. Is it possible to share the code snippets for how to manually pass `ViewContainerRef` to the `NotificationService`?

Thanks in advance!
