### ISSUE TITLE
Out-of-compliance: add missing privacy policy/footer & common js: angular.carbondesignsystem.com

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-components-angular#2774]
See details in umbrella issue https://github.com/carbon-design-system/carbon/issues/15634 🏖️ 

- [Example PR to add footer](https://github.com/carbon-design-system/carbon/pull/15680)
- [Example PR to add common js and footer](https://github.com/carbon-design-system/carbon-platform/pull/1775/files)

**Comment by Akshat55** [comment]
Hey, @alisonjoseph We've added the privacy policy footer to the storybook. Could you please verify the result and close this issue?

https://angular.carbondesignsystem.com/?path=/story/getting-started--welcome
