### ISSUE TITLE
[BUG] Dropdown scrolling issue when navigating using arrow keys

### ISSUE THREAD

**Issue by zubriktomas** [carbon-design-system/carbon-components-angular#2777]
## Detailed bug description

* There is a scrolling problem with `cds-dropdown` component when using arrow keys to navigate between the dropdown list items.
* When trying to navigate up and down between the list items, whole DOM body (in general overflowing container) is scrolled. 
* This is probably only a problem with CDS v11 (Carbon Components Angular v5). In the previous version it was working fine.

## Steps to reproduce the issue

* Use dropdown component in container that has overflow (it is scrollable). 
* Then use arrow keys to navigate through the options. Try different combinations.
* Dropdown will eventually start jumping around because of the scrolling problem.
* It can be easily replicated in documentation demo: https://angular.carbondesignsystem.com/?path=/docs/components-dropdown--docs

https://github.com/carbon-design-system/carbon-components-angular/assets/25706605/5f6e6743-426a-49aa-ac08-2852832eecb7

## Additional information

* This is a major issue in terms of accessibility
* Please, make it a priority as we are working on business critical application packages upgrade and this is a main blocker

**Comment by Akshat55** [comment]
Thanks for reporting this, seems like a recent thing... we had added this implementation a while back and it seemed to work fine.... the repositioning and scrolling into view didn't happen like this before 🤔 

It's also impacting combobox.
