### ISSUE TITLE
[BUG] Close modal view button align issue, tag <cds-modal></cds-modal>, close button is coming down of the header.

### ISSUE THREAD

**Issue by Harshavardhan-Kanoj** [carbon-design-system/carbon-components-angular#2783]
## Detailed description
Modal view close button alignment issue
> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by Harshavardhan-Kanoj** [comment]
I am still seeing this issue after upgrading carbon components to version v5.16.4

**Comment by Akshat55** [comment]
That's odd... It works in storybook now and in my local project - Are you overriding the styles? What version of `@carbon/styles` are you using?

**Comment by Akshat55** [comment]
@Harshavardhan-Kanoj Are you still having this issue?

**Comment by Harshavardhan-Kanoj** [comment]
Yes, I am .

**Comment by Akshat55** [comment]
Could you please post a code sandbox demo of this? I cannot replicate it.
