### ISSUE TITLE
Carbon table with sticky headers shifts header names towards left and content overlap on each other

### ISSUE THREAD

**Issue by SowjanyaKrishnamurthy** [carbon-design-system/carbon-components-angular#2790]
## Additional information
![image (3)](https://github.com/carbon-design-system/carbon-components-angular/assets/160096923/1c6b6845-ad99-4ac6-afd9-b4aea4c8e5b3)

* Screenshots or code
* Notes

**Comment by SowjanyaKrishnamurthy** [comment]
Hi Team, Can you please acknowledge the issue and let us know about the fix

**Comment by Akshat55** [comment]
Acknowledged! Based on react implementation, we need to add white space when single select is enabled and it is a sticky header!
