### ISSUE TITLE
Keep the same style of slider as carbon.

### ISSUE THREAD

**Issue by Sara-Gao** [carbon-design-system/carbon-components-angular#2805]
## Detailed description

> Describe in detail the issue you're having.
Slider component has the different style with Slider in carbon.

> Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?
yes, slider

> What did you expect to happen? What happened instead? What would you like to see changed?
Keep the same style of slider as carbon.
> What browser are you working in?
chrome and firefox

> What version of the Carbon Design System are you using?
Carbon 11

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
![image](https://github.com/carbon-design-system/carbon-components-angular/assets/39545168/419c900c-2518-4217-978e-d013535cf3df)
![image](https://github.com/carbon-design-system/carbon-components-angular/assets/39545168/69fe53b3-83c1-40e4-b6a0-ae59164e9c70)

* Notes

**Comment by Geoffrey0** [comment]
I provided a PR to this as it's also blocking us from adopting the component 👍
