### ISSUE TITLE
[Question]: Why does the custom overflow menu closes on click

### ISSUE THREAD

**Issue by brampeirs** [carbon-design-system/carbon-components-angular#2814]
## Detailed description
The overflow menu with custom template allows you to implement your own template. In our use case we are adding a list of checkboxes, a cancel and save button. The menu closes when clicked however. When looking at the [storybook](https://angular.carbondesignsystem.com/?path=/story/components-overflow-menu--custom), there the issue is reproducable.

https://github.com/carbon-design-system/carbon-components-angular/assets/2495032/249c019c-2e4e-47b6-97ca-adcf03973b3c

> Is this a feature request (new component, new icon), a bug, or a general issue?
[bug]

> Is this issue related to a specific component?
[overflow-menu-custom-pane.component.ts](https://github.com/carbon-design-system/carbon-components-angular/blob/master/src/dialog/overflow-menu/overflow-menu-custom-pane.component.ts#L44)

> What did you expect to happen? What happened instead? What would you like to see changed?
menu should not close, and we should be able to call close() on the menu ourselves. 

> What version of the Carbon Design System are you using?
5.20.2

## Steps to reproduce the issue
[storybook](https://angular.carbondesignsystem.com/?path=/story/components-overflow-menu--custom)

## Additional information
we currently get around this by removing the [onClick](https://github.com/carbon-design-system/carbon-components-angular/blob/master/src/dialog/overflow-menu/overflow-menu-custom-pane.component.ts#L44) logic via patch package.    
and by calling the `close` method ourselves
```
@ViewChild(OverflowMenuDirective) overflowMenu?: OverflowMenuDirective;
 this.overflowMenu?.close();
```

**Comment by Akshat55** [comment]
The custom overflow menu is [deprecated as of v5](https://github.com/carbon-design-system/carbon-components-angular/blob/69eac851e3803ea2952630e4385bffea96fd778a/src/dialog/overflow-menu/overflow-menu-custom-pane.component.ts#L10). Instead, you should use toggletip or popover component.
