### ISSUE TITLE
[BUG]:  Dropdown Component - 'Cannot read properties of undefined' when all the options are disabled

### ISSUE THREAD

**Issue by Aru-Ku** [carbon-design-system/carbon-components-angular#2830]
## Detailed description

When all the options (items) provided to dropdown are disabled, there is an error popping up in the console.

```
ERROR TypeError: Cannot read properties of undefined (reading 'nativeElement')
    at DropdownList.getNextElement (carbon-components-angular-dropdown.mjs:1391:37)
    at DropdownList.updateIndex (carbon-components-angular-dropdown.mjs:1522:18)
    at DropdownList.updateList (carbon-components-angular-dropdown.mjs:1316:14)
    at set items (carbon-components-angular-dropdown.mjs:1266:18)
```

The error is happening in method `getNextElement` in [dropdown-list.component.ts](https://github.com/carbon-design-system/carbon-components-angular/blob/master/src/dropdown/list/dropdown-list.component.ts#L335-L356)

## Cause of the bug

The initial value of `this.index` is `-1`, and since all the `this.displayItems` are having disabled to true, the index value is not getting modified. So, accessing `nativeElement` from `elemList[-1]` will be undefined, the error is happening.

**Comment by Akshat55** [comment]
Interesting we will need to add conditions to address this. Since you've included the function in question, is this a fix you can contribute?

**Comment by Aru-Ku** [comment]
Hi @Akshat55 
Yes, I can work on this. Please assign me this issue.

**Comment by Akshat55** [comment]
Awesome, thank you for taking this on! 🚀
