### ISSUE TITLE
Add ReadOnly state for Text Input

### ISSUE THREAD

**Issue by Akshat55** [carbon-design-system/carbon-components-angular#2901]

**Comment by abiramcodes** [comment]
Hello @Akshat55, I would like work on this issue., 
What do you mean by the readonly state here ?
Can you please elaborate ?

**Comment by Akshat55** [comment]
I've responded in the PR, Ill have to go in and update all of the issues to add more details on how to resolve them. You're on the right track, though!

**Comment by abiramcodes** [comment]
@Akshat55, Thanks for adding more details for the resolution, will make the changes and commit!!
