### ISSUE TITLE
Carbon Design System in Angular 17

### ISSUE THREAD

**Issue by Facundo-ivan-Monzon20** [carbon-design-system/carbon-components-angular#2906]
Is there any support for Angular version 17?
If v5 is listed as future in the repository, is it still not in production?

**Comment by Akshat55** [comment]
Hey @Facundo-ivan-Monzon20, Angular version 17 is supported! [We have an integration test for angular 17](https://github.com/carbon-design-system/carbon-components-angular/tree/master/integration) which passes. Seems like our readme isn't updated, I'll have this addressed.
