### ISSUE TITLE
TreeNodeComponent  TemplateRef label is not supported

### ISSUE THREAD

**Issue by AlexandraMadalina** [carbon-design-system/carbon-components-angular#2913]
## TreeNodeComponent  TemplateRef label is not supported

I'm using the tree view and I need a custom label. The TreeNodeComponent has a label input that can be a string or TemplateRef, but there is no support for the lates. Also for the icon template we don't get the context.

**Comment by Akshat55** [comment]
A fix should be merged next week Tuesday
