### ISSUE TITLE
Future proof routerExtras implementation

### ISSUE THREAD

**Issue by klaascuvelier** [carbon-design-system/carbon-components-angular#2924]
The fix done for #2911 is not the most future proof implementation. Whenever Angular decides to change the properties of the `routerExtra` the implementation might break. (As already happened during the implementation of the fix).

This issue serves to find a better approach.

@Licen-it it suggested to create new directive that extends the `routerLink` functionality to also add the routerExtras.
Can you describe how you see this? Is this a new directive like `routerLinkExtras` that should also be added on the a tag? Or do you want it to really `extend` the `routerLink`? Where would this directive live in the repo? 

Thanks 🙇

**Comment by Licen-it** [comment]
@klaascuvelier just pushed the solution
