### ISSUE TITLE
Combobox value safety (in case of undefined)

### ISSUE THREAD

**Issue by huineng** [carbon-design-system/carbon-components-angular#2931]
I refer to this code

https://github.com/carbon-design-system/carbon-components-angular/blob/17da1f582953ad7538878525d1a254fcdf81e905/src/combobox/combobox.component.ts#L604

There can be circumstances that value is undefined

If that is the case and the type is multi, it will generate an error (value is not iterable)

I simply suggest to add an if statement

```
if (value) {
	for (const v of value) {
		for (const item of this.view.getListItems()) {
			if (item[this.itemValueKey] === v) {
				newValues.push(Object.assign({}, item, { selected: true }));
			}
		}
	}
}
```

 "carbon-components-angular": "^5.27.4"

thanks

**Comment by yuvraj-proarch** [comment]
I'm also getting console error: `value is not iterable`
