### ISSUE TITLE
Paths to fonts can't be resolved

### ISSUE THREAD

**Issue by bstrob** [carbon-design-system/carbon-components-angular#2948]
## Detailed description

After running `npm start` I am getting multiple errors. The errors are always the same. Resolving the path to the IBM Plex-Font:

```
✘ [ERROR] Could not resolve "~@ibm/plex/IBM-Plex-Serif/fonts/split/woff/IBMPlexSerif-SemiBoldItalic-Latin1.woff" [plugin angular-css-resource]

    src/styles.scss:953:168:
      953 │ ...f2"), url("../node_modules/@carbon/styles/scss/fonts||file:~@i...
          ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can remove the tilde and use a relative path to reference it, which should remove this error.
  Preprocessor stylesheets may not show the exact file location of the error.
```

As I remember correctly, Angular stopped supporting using the tilde in Sass files with Angular 13. If I remove the tilde in the file `node_modules/@carbon/styles/scss/_config.scss` in line 44, the errors disappear and the app builds correctly.

Current versions used: 

```
"@carbon/styles": "^1.61.0",
"carbon-components-angular": "^5.28.4"
```

Angular CLI: 18.1.2
Node: 20.16.0
Package Manager: npm 10.8.1
OS: darwin arm64

Angular: 18.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

## Steps to reproduce the issue

See the current "Getting started" steps

1. Run `npx @angular/cli new my-project --style=scss` to create a new project
2. Change directory: `cd my-project`
3. Install dependencies: `npm i --save carbon-components-angular @carbon/styles`
4. Include carbon-components in src/styles.scss with `@use "@carbon/styles";`
5. Run `npm start`

**Comment by Akshat55** [comment]
You need to update the variable pointing to the font as such:

```scss
@use '@carbon/styles/scss/config' with (
	$use-flexbox-grid: true,
	$font-path: '@ibm/plex' // Since Angular doesn't support `~` imports anymore, we can rewrite the path by updating the config
);
```

**Comment by bstrobach** [comment]
Okay, thanks. Maybe this should be reflected more in the readme file. Shall I create a PR?

**Comment by bstrob** [comment]
Okay, thanks. Maybe this should be reflected more in the readme file. Shall I create a PR?

**Comment by fstendel** [comment]
Sorry, for hijacking this. 
As I also stumbled across this, I'm curious why the underlying issue isn't/can't be fixed?
(I'm likely not as proficient in Angular as you guys. So if this is a dumb question, again: Sorry)
