### ISSUE TITLE
Toggle indeterminate state has no effect

### ISSUE THREAD

**Issue by kasar-NTT** [carbon-design-system/carbon-components-angular#2949]
## Detailed description

> Describe in detail the issue you're having.
Toggle indeterminate state has no effect 

> Is this a feature request (new component, new icon), a bug, or a general issue?
BUG

> Is this issue related to a specific component?
Toggle

> What did you expect to happen? What happened instead? What would you like to see changed?
I would expect to see the "Indeterminate state" as in Checkbox component

> What browser are you working in?
Chrome: Version 127.0.6533.72 (Official Build) (64-bit)

> What version of the Carbon Design System are you using? 
Latest (even in the official docs this is not working)

## Steps to reproduce the issue
Visti the official docs: https://angular.carbondesignsystem.com/?path=/story/components-toggle--basic&args=indeterminate:!true

## Additional information

* Screenshots or code
![image](https://github.com/user-attachments/assets/f6ae1cde-28d8-4b11-ba13-d5b8f4387791)

**Comment by Akshat55** [comment]
Thanks for reporting this, `indeterminate` should be removed from the storybook. After taking a further look at the code, the component should not be extending Checkbox to begin with. Starting v11, toggle implementation was separated from Checkbox, but I'm guessing was kept for sake of backwards comparability.

It doesn't make sense to have `indeterminate` state, it is a `switch`, it is either `on` or `off`.

**Comment by kasar-NTT** [comment]
That makes sense. I just wanted to verify this is not supported.

Thanks for the quick reply 😄

**Comment by Akshat55** [comment]
I'll add a note to remove this inheritance starting v12
