### ISSUE TITLE
Memory leak while using an overflow menu inside the tree view component while navigating

### ISSUE THREAD

**Issue by Ornco** [carbon-design-system/carbon-components-angular#3003]
## Detailed description

> Describe in detail the issue you're having.

The design I am working on needs an overflow menu inside the tree view component which seems to be causing a memory leak coming along with navigation

> Is this a feature request (new component, new icon), a bug, or a general issue?

Seems to be a bug

> Is this issue related to a specific component?

Yes - the  overflow menu component

> What did you expect to happen? What happened instead? What would you like to see changed?

I would expect there to be no memory leak.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

5.28.3

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Zelta

## Steps to reproduce the issue
Create a tree view with a node list and render an overflow menu with each node.

1. Check the sandbox link below and open the preview in it's own tab
2. Start profiling the performance 
3. Click the 'Click me to reset table button' a few times (the more you press the better, maybe 20/30+).
4. Stop profiling and view the leak.

<img width="1005" alt="image" src="https://github.com/user-attachments/assets/cdaf5538-506a-4430-8347-fa384a9883c8">

https://codesandbox.io/p/sandbox/carbon-components-angular-forked-mpx7kf

## Additional information
A similar leak was also seen for overflow menus inside the cds-table-toolbar-content component and for overflow menus in nested tables

[Update]
I'm not sure if it is related but I attached another sandbox for a similar issue noticed with combo boxes containing a large number of options (>500) in our case. This one isn't just a memory leak but also has performance implications. The more there are the worse the performance gets. The memory leak can be seen by adding more or simply toggling them on/off via the buttons at the top. If i need to open another issue please let me know. Otherwise I'll just leave this here for now. Thanks in advance.

https://codesandbox.io/p/sandbox/carbon-components-angular-forked-mz84kd

**Comment by eduardmarcinco** [comment]
This one is interesting. 
I tracked the memory leak down to `EventService`. This service is used to track subscriptions to event listeners for DOM events, but service never unsubscribes from them and garbage collector cannot clean them up properly.

[EventService](https://github.com/carbon-design-system/carbon-components-angular/blob/master/src/utils/event.service.ts) implements `ngOnDestroy` but `EventService` is in providers array for `UtilsModule` [(defined here)](https://github.com/carbon-design-system/carbon-components-angular/blob/master/src/utils/utils.module.ts#L42).

`UtilsModule` is imported by many modules including `DialogModule`.

Woudnt it make sense to have an instance of `EventService` for each component that is using it? 
When component is destroyed, all it's associated event listeners would be removed and cleaned up by GC.

I understand this may be a breaking change. But the memory leak is definitely there.

Example of `DialogDirective` that is registering multiple event listeners:
https://github.com/carbon-design-system/carbon-components-angular/blob/master/src/dialog/dialog.directive.ts#L185-L226

@Akshat55 fyi ^^

**Comment by eduardmarcinco** [comment]
@Ornco can you make that second codesandbox public? I cant open it.

https://codesandbox.io/p/sandbox/carbon-components-angular-forked-mz84kd

`It's likely that the Sandbox you're trying to access doesn't exist or you don't have the required permissions to access it.`

**Comment by Ornco** [comment]
@eduardmarcinco apologies yes it was private. I've made it public now so you can access. Thanks for looking in to this.

**Comment by Akshat55** [comment]
I definitely want to rework/remove a lot of the `Utils` services and simplify them, they seem over engineered for what they do in my opinion. 

> Example of DialogDirective that is registering multiple event listeners:
> https://github.com/carbon-design-system/carbon-components-angular/blob/master/src/dialog/dialog.directive.ts#L185-L226

I'm aware of this, the simple fix I can think of is to manually call the event service OnDestroy from dialog directive OnDestroy. 

```ts
	/**
	 * When the host dies, kill the popover.
	 * - Useful for use in a modal or similar.
	 */
	ngOnDestroy() {
		this.close({
			reason: CloseReasons.destroyed
		});
		// Unsubscribe & delete the subscriptions
		this.eventService.ngOnDestroy();
	}
```
But I don't know if that would create any issues for some of the existing components.... my assumption is that it wouldn't since EventService is not a singleton, but more testing would be required.

As of v11, only overflow menu uses dialog directive. So, in next release, the plan is to remove `DialogModule` and create a new `OverflowModule` which uses `floating-ui` for positioning. A possible `OverflowMenuV2` can be released as part of this fix to help users transition 🤔

**Comment by Licen-it** [comment]
@Akshat55 even if it's not a singleton it would be the same shared instance for the entire module where it's imported in, so it would be a singleton within the importing module. What you are suggesting might create issues. In any case i don't think it would make any sense for an injectable to implement `onDestroy` or any other lifecycle hooks, since they are ignored for injectables according to documentation. You could consider it not being an injectable and create an instance of that class each time you need to use it, this way you can handle the onDestroy the way you proposed above

**Comment by eduardmarcinco** [comment]
Potentially, as a quick fix `EventService` can be added to providers array in `OverflowMenuDirective`.
That would force Angular to create a new instance of `EventService` for each Overflow menu.
When overflow menu is being destroyed, `ngOnDestroy` in EventService will be called automatically.

```typescript
@Directive({
	selector: "[cdsOverflowMenu], [ibmOverflowMenu]",
	exportAs: "overflowMenu",
	providers: [
		DialogService,
                EventService 
	]
})
export class OverflowMenuDirective extends DialogDirective {
```

**Comment by Licen-it** [comment]
> Potentially, as a quick fix `EventService` can be added to providers array in `OverflowMenuDirective`. That would force Angular to create a new instance of `EventService` for each Overflow menu. When overflow menu is being destroyed, `ngOnDestroy` in EventService will be called automatically.
> 
> @Directive({
> 	selector: "[cdsOverflowMenu], [ibmOverflowMenu]",
> 	exportAs: "overflowMenu",
> 	providers: [
> 		DialogService,
>                 EventService 
> 	]
> })
> export class OverflowMenuDirective extends DialogDirective {

Are you sure it will be a new instance for each new instance of the directive? As it should follow the module pattern, so defining it there it would be like having a module with just that directive and therefore i would expect a singleton for all directive instances

**Comment by eduardmarcinco** [comment]
Yes, directive / component providers array takes precedence over module providers.
See: https://angular.dev/guide/di/hierarchical-dependency-injection#resolution-rules

Also I've tested it locally.
```typescript
@Injectable()
export class EventService implements OnDestroy {
	...

	constructor(protected documentService: DocumentService) {
		console.log("EventService", "constructor");
	}

        ...

	ngOnDestroy() {
		this.subscriptions.unsubscribe();
		console.log("EventService", "ngOnDestroy");
	}
}
```

Resetting the tree removes Overflow menu from the DOM and re-add it couple of ms later.

![Image](https://github.com/user-attachments/assets/03de7f4a-10b5-42d6-b723-b4de70c9bc39)


![Image](https://github.com/user-attachments/assets/8bdb3903-0d3f-4053-9529-e24e04ba7364)

**Comment by Licen-it** [comment]
> Yes, directive / component providers array takes precedence over module providers. See: https://angular.dev/guide/di/hierarchical-dependency-injection#resolution-rules
> 

No i meant that if you create in the same page multiple instances of that directive...if the service might have been shared across all the instances, but reading the documentation link above, even if not said explicitly, it seems each component would have its own instance
