### ISSUE TITLE
Modals are not reopening if we close it by clicking ESC button

### ISSUE THREAD

**Issue by SowjanyaKrishnamurthy** [carbon-design-system/carbon-components-angular#3004]
## Detailed description

> Describe in detail the issue you're having.
After closing the modal onclick of ESC Button, we are not able to open any of the modal in the application. 

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
Modals

> What did you expect to happen? What happened instead? What would you like to see changed?
If we close the modals by clicking ESC button, we should be able to open again. Instead none of the modals are opening after closing modal by ESC button.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
"carbon-components-angular": "^5.28.1",
"@carbon/icons": "^11.45.0",
"@carbon/styles": "^1.61.0",
"@carbon/type": "^11.25.0",

## Steps to reproduce the issue

Step 1: Open any modal
Step 2: Close by clicking ESC button
Step 3: Open modal again

**Comment by SowjanyaKrishnamurthy** [comment]
Hi @eduardmarcinco,
You can create a sample modal with "carbon-components-angular": "^5.28.1" version.
Step 1: Open a Modal
Step 2: press ESC button, modal gets closed
Step 3: try to open modal again

**Comment by eduardmarcinco** [comment]
I was able to see the issue in this story -> https://angular.carbondesignsystem.com/?path=/story/components-modal--simple

If you use this way of creating modals, you need to add `(close)="open = false"` on `cds-modal` element.

Example:
```
<button #trigger cdsButton="primary" (click)="open = true">Open</button>
  <cds-modal [open]="open" [trigger]="trigger" (overlaySelected)="open = false" (close)="open = false">
  ... 
```

Does this fix your issue?

**Comment by SowjanyaKrishnamurthy** [comment]
Hi, The above solution works. Thank you so much
