### ISSUE TITLE
[BUG] ComboBoxComponent and DropdownComponent have conflicting ids

### ISSUE THREAD

**Issue by darginyegor** [carbon-design-system/carbon-components-angular#3022]
both ComboBoxComponent and DropdownComponent assign ids to their labels and control element using `'dropdown-'` prefix:

https://github.com/carbon-design-system/carbon-components-angular/blob/60c3a445c0410f8e823e4de8bf99a66e01e481ff/src/combobox/combobox.component.ts#L266

https://github.com/carbon-design-system/carbon-components-angular/blob/60c3a445c0410f8e823e4de8bf99a66e01e481ff/src/dropdown/dropdown.component.ts#L186

this leads to ids conflicting with each other and labels assigned to wrong controls. so, e.g., when u click on a label for dropdown B, combobox A  opens instead

```HTML
<ibm-combo-box label="A"><ibm-combo-box>
<ibm-dropdown label="B"></ibm-dropdown>

<!--

both will have "dropdown-1" as id values on control elements
and B's label will have "dropdown-1" in its "for" attribute,
so clicking on it leads to A's dropdown being opened

-->
```

**Comment by darginyegor** [comment]
here's a pr ready, can't link it to the issue for some reason

https://github.com/carbon-design-system/carbon-components-angular/pull/3023

**Comment by Akshat55** [comment]
Thanks for bringing this to our attention and also creating an issue! keep in mind, this fix will be released in CCA@v5
