### ISSUE TITLE
Angular 18 issue with project setup

### ISSUE THREAD

**Issue by gorgiivanov** [carbon-design-system/carbon-components-angular#3031]
Hi i have an issue with configuration of the project.

Will need components that works in standalone mode.

also i have a lot of errors like 'ibm-modal' is not a known element:...

Tnx

**Comment by Akshat55** [comment]
Hi @gorgiivanov, what issues are you running into? Have you imported `ModalModule`? 

Have you looked at our [Angular 18 integration test](https://github.com/carbon-design-system/carbon-components-angular/tree/master/integration/ng18)?

**Comment by Akshat55** [comment]
Going to close this issue due to inactivity. Feel free to comment/reopen if you're still running into any issues!
