### ISSUE TITLE
incorrect typedefinition for TranslationStrings (fix suggested)

### ISSUE THREAD

**Issue by huineng** [carbon-design-system/carbon-components-angular#3032]
This is an incorrect type definition for TranslationStrings

https://github.com/carbon-design-system/carbon-components-angular/blob/7967695ff011a0e42761f4fcf766820bdd2e1bef/src/i18n/i18n.service.ts#L138C1-L138C60

it should in fact support nested values like in the en.ts file

i suggest to modify it to 

```
export type TranslationStrings = {
  [key: string]: string | { [key: string]: string | TranslationStrings };
};
```

Thanks

latest carbon-angular-components. version

**Comment by klaascuvelier** [comment]
I think you are correct, but I think your suggestion can be simplified to 
```
export type TranslationStrings = {
  [key: string]: string | TranslationStrings;
};
```

I created a [PR](https://github.com/carbon-design-system/carbon-components-angular/pull/3077) where I updated the type :)
