### ISSUE TITLE
Tooltip error thrown when switching the disabled state for a cds-icon-button from true to false.

### ISSUE THREAD

**Issue by koenvd** [carbon-design-system/carbon-components-angular#3049]
To reproduce create a template containing this:

```
<cds-tooltip [autoAlign]="true" [description]="description">
   <cds-icon-button [disabled]="disabled">
   </cds-icon-button>
</cds-tooltip>
```

Then switch disabled to `true`.  Then to `false`. At that moment the following error is thrown:
![Image](https://github.com/user-attachments/assets/66900549-3c00-45b2-9ced-5bdf33146406)

Location where it fails:
![Image](https://github.com/user-attachments/assets/2cc85ca8-3cb7-44ba-acfa-6058653ae787)

In both cases (enabled and disabled) the tooltip still renders fine though.  But somehow the `Tooltip` doesn't find the popover content when switching to the enabled state.

Fix can be to just play safe and only call `setAttribute` when the popover content was found. So in `tooltip.component.ts` just do
```
this.popoverContentRef = this.elementRef.nativeElement.querySelector(".cds--popover-content");
this.popoverContentRef?.setAttribute("style", "");
```

But I think something more fundamental is going wrong if I read the comments above those lines. 

Probably there's a better fix?

**Comment by Akshat55** [comment]
@koenvd What you're currently doing is wrapping a tooltip within a tooltip and I believe that is causing this issue. For accessibility purpose, starting v11, `cds-icon-button` component is wrapped in `cds-tooltip`.

To resolve this, you can change the above code to the following:

```html
<cds-icon-button
   [disabled]="disabled"
   [autoAlign]="true"
   [description]="description">
   <svg class="cds--btn__icon" cdsIcon="copy" size="16"></svg>
</cds-icon-button>
```

**Comment by koenvd** [comment]
Indeed that resolves the error @Akshat55 .

But I noticed before the tooltip was appearing when the button was disabled. So we could explain in the tooltip why the button was disabled.  Now the tooltip is not appearing when the button is disabled. 

Not sure there's a way to do that?

**Comment by klaascuvelier** [comment]
@Akshat55 when you say 

> I'll see if I can add ...

Does this mean you need to check if it's feasible, or that you want to do it yourself? 
Because I (or anyone else) could be up to take a look at this.

**Comment by Akshat55** [comment]
Check if it's feasible + compare it to v4 implementation.

I did verify it and found that v4 did show tooltips when icon button was disabled. @klaascuvelier Feel free to contribute a PR for this @klaascuvelier.

**Comment by klaascuvelier** [comment]
If I understand correctly, the tooltip was always shown, so we don't need an extra input for it to be true/false @Akshat55 ?
