### ISSUE TITLE
Codesandbox does not work anymore to reproduce issues

### ISSUE THREAD

**Issue by Geoffrey0** [carbon-design-system/carbon-components-angular#3057]
The current codesandbox in the readme does not work anymore https://codesandbox.io/s/0129r494ql. It would help with reproducing issues if we can get a working version in there. 

I had a first go at creating a template of a devbox in codesandbox https://codesandbox.io/p/devbox/carbon-components-angular-55c5qr, can drop an MR to update it if wanted.

**Comment by Geoffrey0** [comment]
I think stackblitz would definitely be the better option! I created the codesandbox as I thought that would be the prefered option. Glad to hear other opinions.

**Comment by klaascuvelier** [comment]
I have a very basic example in stackblitz: https://stackblitz.com/edit/stackblitz-starters-qfh9hw?file=src%2Fmain.ts

**Comment by Akshat55** [comment]
Awesome, definitely easier than using codesandbox! Could you please create a PR to replace existing code sandbox link in readme/ISSUE_TEMPLATE?

**Comment by klaascuvelier** [comment]
Is it okay to use the stackblitz that I created? Don't you want to fork it, so you own it as repo owners, or get it owned by the company?
For me it's fine either way :)

**Comment by Akshat55** [comment]
Just verified with the team, we can just go with an anonymous stackblitz for now:

https://stackblitz.com/edit/stackblitz-starters-exxkq4?file=src%2Fmain.ts
