### ISSUE TITLE
[bug] Combobox needs to map disabled values according to itemValueKey on clearSelected

### ISSUE THREAD

**Issue by stijndeschuymer** [carbon-design-system/carbon-components-angular#3063]
Combobox needs to map disabled values according to itemValueKey on clearSelected.

I'll be submitting a PR with a fix soon.

**Comment by Akshat55** [comment]
> Combobox needs to map disabled values according to itemValueKey on clearSelected.

Could you provide some more context on this? Why is this a bug? What is the current result? What is the expected result?

I'm confused because when the combo box clearSelected is called, the output should be an empty array AFTER all list items selected state is set to false.

**Comment by stijndeschuymer** [comment]
As this comment in the code shows: https://github.com/carbon-design-system/carbon-components-angular/pull/3064/files#diff-c162199cd5e798879e7cd8b55e42def0e32ac187f4abdbddf5ffe17b19a9251aR681

So usually when `clearSelected` is called, the output should indeed be empty, unless when there are selected items that are disabled!
Thats the issue.
When there are 'selected'+'disabled' items, those items are emitted, 
Current result: the entire object for those items is emitted and the object is not mapped to a provided itemValueKey
Expected result: the emitted objects are mapped according to itemValueKey as fixed in this PR:  https://github.com/carbon-design-system/carbon-components-angular/pull/3064

**Comment by Akshat55** [comment]
Thanks for the explanation, I was able to reproduce this issue.
