### ISSUE TITLE
debounce and control dialog opening

### ISSUE THREAD

**Issue by cal-smith** [carbon-design-system/carbon-components-angular#662]
From Dustin on slack:

> So the idea is that we don't want to make the service call if the user is just navigating over to something else and happened to mouse into our tooltipped element. And also that the tooltip wouldn't display until the service call returns with the necessary data.

Effectively the core requirement is a debounceable hover + more control over when the dialg opens (perhaps the content could accept an observable and we delay opening until it resolves?)

**Comment by Akshat55** [comment]
I believe this was addressed in v4 and in v5 we switch over to inline tooltips so dialog is no longer applicable. Closing this issue as it is now invalid.
